// antiFraud.ts - 200+ вопросов для Anti-Fraud Specialist

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const antiFraudQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (25) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте работы в антифроде." },
  { stage: "Background", difficulty: 1, text: "Что привлекло вас в сферу борьбы с мошенничеством?" },
  { stage: "Background", difficulty: 1, text: "С какими типами мошенничества вы знакомы?" },
  { stage: "Background", difficulty: 1, text: "Какое у вас образование?" },
  { stage: "Background", difficulty: 1, text: "Какие инструменты аналитики вы использовали?" },
  { stage: "Background", difficulty: 2, text: "В каких индустриях вы работали (банки, финтех, e-commerce)?" },
  { stage: "Background", difficulty: 2, text: "Какие инструменты и системы антифрода вы использовали?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о самом интересном кейсе мошенничества." },
  { stage: "Background", difficulty: 2, text: "С какими объемами транзакций вы работали?" },
  { stage: "Background", difficulty: 2, text: "Как вы попали в антифрод?" },
  { stage: "Background", difficulty: 3, text: "Опишите команду, в которой вы работали." },
  { stage: "Background", difficulty: 3, text: "Какой был ваш вклад в снижение уровня мошенничества?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте работы с регуляторами." },
  { stage: "Background", difficulty: 3, text: "Как вы взаимодействовали с другими командами?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте работы с внешними поставщиками данных." },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте построения антифрод-команды." },
  { stage: "Background", difficulty: 4, text: "Как вы определяли стратегию антифрода?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте работы с law enforcement." },
  { stage: "Background", difficulty: 4, text: "Как вы оценивали ROI антифрод-инициатив?" },
  { stage: "Background", difficulty: 5, text: "Как вы выстраивали взаимодействие антифрода с другими подразделениями?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте работы с board level." },
  { stage: "Background", difficulty: 5, text: "Как вы строили fraud prevention culture?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте работы с consortium data." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли risk appetite для компании?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте работы с международными fraud cases." },

  // ========== CORE (70) ==========
  { stage: "Core", difficulty: 1, text: "Какие основные типы мошенничества существуют в онлайн-платежах?", expectedKeywords: ["carding", "ATO", "friendly fraud"] },
  { stage: "Core", difficulty: 1, text: "Что такое chargeback и почему он важен?", expectedKeywords: ["chargeback", "dispute", "refund"] },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между fraud и friendly fraud." },
  { stage: "Core", difficulty: 1, text: "Что такое KYC и зачем он нужен?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое AML." },
  { stage: "Core", difficulty: 1, text: "Что такое транзакционный мониторинг?" },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между prevention и detection." },
  { stage: "Core", difficulty: 1, text: "Что такое false positive в контексте антифрода?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое risk score." },
  { stage: "Core", difficulty: 2, text: "Какие данные о транзакции важны для оценки риска?", expectedKeywords: ["amount", "device", "IP", "behavior"] },
  { stage: "Core", difficulty: 2, text: "Что такое device fingerprinting?", expectedKeywords: ["fingerprint", "device", "identification"] },
  { stage: "Core", difficulty: 2, text: "Расскажите о базовых правилах (rules) в антифрод-системе." },
  { stage: "Core", difficulty: 2, text: "Что такое velocity checks?", expectedKeywords: ["velocity", "frequency", "limit"] },
  { stage: "Core", difficulty: 2, text: "Объясните, что такое BIN (Bank Identification Number)." },
  { stage: "Core", difficulty: 2, text: "Что такое 3D Secure?" },
  { stage: "Core", difficulty: 2, text: "Объясните CVV и AVS checks." },
  { stage: "Core", difficulty: 2, text: "Что такое geolocation в антифроде?" },
  { stage: "Core", difficulty: 2, text: "Объясните IP reputation." },
  { stage: "Core", difficulty: 2, text: "Что такое email risk scoring?" },
  { stage: "Core", difficulty: 2, text: "Объясните phone verification." },
  { stage: "Core", difficulty: 2, text: "Что такое behavioral biometrics?" },
  { stage: "Core", difficulty: 2, text: "Объясните session analysis." },
  { stage: "Core", difficulty: 3, text: "Как вы проектируете правила для антифрод-системы?" },
  { stage: "Core", difficulty: 3, text: "Какие источники данных вы используете для оценки риска?" },
  { stage: "Core", difficulty: 3, text: "Как вы балансируете между false positive и false negative?", expectedKeywords: ["precision", "recall", "business impact"] },
  { stage: "Core", difficulty: 3, text: "Расскажите о KYC/AML и их связи с антифродом." },
  { stage: "Core", difficulty: 3, text: "Как работает 3D Secure и какие есть ограничения?" },
  { stage: "Core", difficulty: 3, text: "Что такое risk scoring и как он рассчитывается?" },
  { stage: "Core", difficulty: 3, text: "Объясните account takeover (ATO) detection." },
  { stage: "Core", difficulty: 3, text: "Что такое synthetic identity fraud?" },
  { stage: "Core", difficulty: 3, text: "Объясните promo abuse и bonus hunting." },
  { stage: "Core", difficulty: 3, text: "Что такое return fraud?" },
  { stage: "Core", difficulty: 3, text: "Объясните affiliate fraud." },
  { stage: "Core", difficulty: 3, text: "Что такое seller fraud на маркетплейсах?" },
  { stage: "Core", difficulty: 3, text: "Объясните click fraud." },
  { stage: "Core", difficulty: 3, text: "Что такое identity verification?" },
  { stage: "Core", difficulty: 3, text: "Объясните document verification." },
  { stage: "Core", difficulty: 3, text: "Что такое liveness detection?" },
  { stage: "Core", difficulty: 4, text: "Как вы проектируете многоуровневую систему защиты?" },
  { stage: "Core", difficulty: 4, text: "Расскажите о вашем опыте с ML-моделями в антифроде." },
  { stage: "Core", difficulty: 4, text: "Как вы работаете с graph analytics для fraud detection?" },
  { stage: "Core", difficulty: 4, text: "Объясните link analysis." },
  { stage: "Core", difficulty: 4, text: "Что такое network analysis в антифроде?" },
  { stage: "Core", difficulty: 4, text: "Объясните anomaly detection approaches." },
  { stage: "Core", difficulty: 4, text: "Как вы работаете с unbalanced datasets?" },
  { stage: "Core", difficulty: 4, text: "Объясните real-time vs batch scoring." },
  { stage: "Core", difficulty: 4, text: "Что такое fraud orchestration platform?" },
  { stage: "Core", difficulty: 4, text: "Объясните case management system." },
  { stage: "Core", difficulty: 5, text: "Как вы интегрируете антифрод в real-time processing pipeline?" },
  { stage: "Core", difficulty: 5, text: "Объясните consortium data sharing." },
  { stage: "Core", difficulty: 5, text: "Как вы работаете с cross-border fraud?" },
  { stage: "Core", difficulty: 5, text: "Объясните PSD2/SCA requirements." },
  { stage: "Core", difficulty: 5, text: "Что такое liability shift?" },
  { stage: "Core", difficulty: 5, text: "Объясните fraud-as-a-service (FaaS)." },
  { stage: "Core", difficulty: 5, text: "Как вы работаете с organized fraud rings?" },
  { stage: "Core", difficulty: 5, text: "Объясните money mule detection." },
  { stage: "Core", difficulty: 5, text: "Что такое first-party fraud?" },
  { stage: "Core", difficulty: 5, text: "Объясните bust-out fraud." },
  { stage: "Core", difficulty: 5, text: "Как вы работаете с deep fake fraud?" },
  { stage: "Core", difficulty: 5, text: "Объясните voice fraud detection." },

  // ========== SQL (25) ==========
  { stage: "SQL", difficulty: 2, text: "Напишите запрос для поиска пользователей с более чем 5 транзакциями за час." },
  { stage: "SQL", difficulty: 2, text: "Как найти дублирующиеся транзакции по сумме и времени?" },
  { stage: "SQL", difficulty: 2, text: "Напишите запрос для расчета chargeback rate по merchant." },
  { stage: "SQL", difficulty: 2, text: "Напишите запрос для поиска транзакций без 3DS." },
  { stage: "SQL", difficulty: 2, text: "Как найти новые устройства для пользователя?" },
  { stage: "SQL", difficulty: 3, text: "Как найти пользователей с транзакциями из разных стран за день?" },
  { stage: "SQL", difficulty: 3, text: "Напишите запрос для velocity check: сумма > $1000 за 15 минут." },
  { stage: "SQL", difficulty: 3, text: "Как найти связанные аккаунты по device_id?" },
  { stage: "SQL", difficulty: 3, text: "Напишите запрос для поиска аномальных сумм транзакций." },
  { stage: "SQL", difficulty: 3, text: "Как посчитать fraud rate по BIN ranges?" },
  { stage: "SQL", difficulty: 3, text: "Напишите запрос для расчета average fraud amount по category." },
  { stage: "SQL", difficulty: 3, text: "Как найти пользователей с резким изменением поведения?" },
  { stage: "SQL", difficulty: 4, text: "Напишите запрос для построения графа связей между аккаунтами." },
  { stage: "SQL", difficulty: 4, text: "Как найти patterns в времени транзакций (bot behavior)?" },
  { stage: "SQL", difficulty: 4, text: "Напишите запрос для sessionization fraud events." },
  { stage: "SQL", difficulty: 4, text: "Как посчитать first-party fraud indicators?" },
  { stage: "SQL", difficulty: 4, text: "Напишите запрос для money mule detection patterns." },
  { stage: "SQL", difficulty: 4, text: "Напишите запрос для cohort analysis по fraud rate." },
  { stage: "SQL", difficulty: 4, text: "Как построить feature для ML модели из SQL?" },
  { stage: "SQL", difficulty: 5, text: "Как оптимизировать запрос для real-time fraud scoring?" },
  { stage: "SQL", difficulty: 5, text: "Напишите запрос для bust-out detection." },
  { stage: "SQL", difficulty: 5, text: "Как построить fraud network analysis в SQL?" },
  { stage: "SQL", difficulty: 5, text: "Напишите запрос для расчета fraud attribution." },
  { stage: "SQL", difficulty: 5, text: "Как организовать историческое сравнение fraud patterns?" },
  { stage: "SQL", difficulty: 5, text: "Напишите запрос для cross-merchant fraud analysis." },

  // ========== DEEP DIVE (35) ==========
  { stage: "DeepDive", difficulty: 3, text: "Опишите сложный кейс мошенничества, который было трудно обнаружить." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы анализируете паттерны мошенничества?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте расследования инцидентов." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы работаете с false positives?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте настройки правил." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы приоритизируете alerts?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте работы с queue management." },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте работы с manual review queue." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы обучаете новых fraud analysts?" },
  { stage: "DeepDive", difficulty: 4, text: "Как вы проектировали или улучшали скоринговую модель риска?" },
  { stage: "DeepDive", difficulty: 4, text: "Как вы оцениваете эффективность антифрод-системы?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте работы с graph analytics." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы настраиваете мониторинг и алерты?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте A/B testing правил." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с feature engineering для fraud models?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с real-time scoring." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы документируете fraud patterns?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с fraud simulation." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с feedback loop от disputes?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте оптимизации review process." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с SLA для fraud review?" },
  { stage: "DeepDive", difficulty: 5, text: "Как вы боролись с адаптацией мошенников к вашим правилам?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с consortium data." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите fraud prevention strategy?" },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете knowledge management в антифрод-команде?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте работы с external fraud vendors." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите fraud reporting для management?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с fraud loss forecasting." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите fraud budget planning?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с regulatory audits." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете cross-functional fraud initiatives?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с vendor evaluation." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с product team по fraud-safe design?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с fraud communication to customers." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите fraud resilience в организации?" },

  // ========== CASE (30) ==========
  { stage: "Case", difficulty: 2, text: "Пользователь жалуется на блокировку платежа. Как разберетесь?" },
  { stage: "Case", difficulty: 2, text: "Вы видите транзакцию с нового устройства на крупную сумму. Какие проверки?" },
  { stage: "Case", difficulty: 2, text: "Как бы вы объяснили пользователю причину блокировки?" },
  { stage: "Case", difficulty: 2, text: "Merchant жалуется на высокий decline rate. Что делать?" },
  { stage: "Case", difficulty: 3, text: "Выросло количество chargeback по картам определённого банка. Как расследуете?" },
  { stage: "Case", difficulty: 3, text: "Нужно внедрить временные правила против новой волны фрода." },
  { stage: "Case", difficulty: 3, text: "Как бы вы настроили антифрод для P2P переводов?" },
  { stage: "Case", difficulty: 3, text: "Мошенники начали использовать VPN. Как адаптируете правила?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы расследовали suspected promo abuse?" },
  { stage: "Case", difficulty: 3, text: "Merchant сообщает о suspected friendly fraud. Ваши действия?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы настроили правила для high-risk category?" },
  { stage: "Case", difficulty: 3, text: "Обнаружили паттерн triangulation fraud. Как отреагируете?" },
  { stage: "Case", difficulty: 4, text: "Как спроектировать антифрод для функции 'перевод по номеру телефона'?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы построили систему для выявления account takeover?" },
  { stage: "Case", difficulty: 4, text: "Запускается новый продукт. Как спроектируете антифрод с нуля?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы организовали fraud review для 24/7 операций?" },
  { stage: "Case", difficulty: 4, text: "Обнаружили coordinated attack. Как отреагируете в real-time?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы спроектировали merchant onboarding fraud checks?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали real-time fraud detection для 10M+ транзакций в день?" },
  { stage: "Case", difficulty: 5, text: "Конкурент переманивает ваших fraud-аналитиков. Как сохраните knowledge?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили cross-border fraud prevention?" },
  { stage: "Case", difficulty: 5, text: "Regulator требует улучшить fraud reporting. Как организуете?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали fraud prevention для crypto payments?" },
  { stage: "Case", difficulty: 5, text: "Board требует сократить fraud losses на 30%. Ваш план?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали fraud prevention для BNPL product?" },
  { stage: "Case", difficulty: 5, text: "Обнаружили insider threat. Как расследуете?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали fraud prevention для marketplace?" },
  { stage: "Case", difficulty: 5, text: "Нужно интегрировать ML model в existing rules engine." },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали fraud prevention для gaming/gambling?" },
  { stage: "Case", difficulty: 5, text: "Competitor получил data breach, атаки переключились на вас. Ваши действия?" },

  // ========== DEBUG (15) ==========
  { stage: "Debug", difficulty: 2, text: "Правило блокирует слишком много транзакций. Как найдёте причину?" },
  { stage: "Debug", difficulty: 2, text: "False positive rate резко вырос. С чего начнете расследование?" },
  { stage: "Debug", difficulty: 3, text: "Резко выросло количество заблокированных честных пользователей." },
  { stage: "Debug", difficulty: 3, text: "Модель начала пропускать фрод. Как диагностируете?" },
  { stage: "Debug", difficulty: 3, text: "Velocity rule срабатывает на legitimate business." },
  { stage: "Debug", difficulty: 3, text: "3DS started failing for specific issuer. Ваши действия?" },
  { stage: "Debug", difficulty: 4, text: "Ошибка в интеграции привела к неверной оценке риска." },
  { stage: "Debug", difficulty: 4, text: "После обновления модели выросли потери." },
  { stage: "Debug", difficulty: 4, text: "Device fingerprinting перестал работать корректно." },
  { stage: "Debug", difficulty: 4, text: "Graph database показывает inconsistent results." },
  { stage: "Debug", difficulty: 5, text: "Обнаружен внутренний fraud. Как будете расследовать?" },
  { stage: "Debug", difficulty: 5, text: "Регулятор нашёл нарушения в вашей системе. Как исправите?" },
  { stage: "Debug", difficulty: 5, text: "Произошла утечка fraud rules. Как отреагируете?" },
  { stage: "Debug", difficulty: 5, text: "ML модель показывает bias против определённой группы." },
  { stage: "Debug", difficulty: 5, text: "После инцидента потеряли доверие stakeholders. Как восстановите?" },

  // ========== WRAPUP (10) ==========
  { stage: "WrapUp", difficulty: 1, text: "Что вам нравится в работе антифрод-специалиста?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие навыки хотите развить?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы следите за новыми fraud trends?" },
  { stage: "WrapUp", difficulty: 3, text: "Какие инструменты или подходы хотели бы изучить?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы видите будущее антифрода с развитием AI?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в мошенничестве вас беспокоят?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы относитесь к этическим вопросам в антифроде?" },
  { stage: "WrapUp", difficulty: 5, text: "Как изменится роль fraud специалиста в будущем?" },
  { stage: "WrapUp", difficulty: 5, text: "Какой вклад вы хотите внести в индустрию?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие challenges в антифроде вас привлекают?" },
];

