// backend.ts - 200+ вопросов для Backend Developer

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const backendQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (25) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте backend разработки." },
  { stage: "Background", difficulty: 1, text: "Какие языки программирования вы используете?", expectedKeywords: ["Python", "Java", "Go", "Node"] },
  { stage: "Background", difficulty: 1, text: "Какие фреймворки вы использовали?" },
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем образовании и как вы пришли в программирование." },
  { stage: "Background", difficulty: 1, text: "С какими базами данных вы работали?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о самом интересном проекте." },
  { stage: "Background", difficulty: 2, text: "Как была организована работа в вашей команде?" },
  { stage: "Background", difficulty: 2, text: "Какие практики разработки вы применяете (CI/CD, code review)?" },
  { stage: "Background", difficulty: 2, text: "С какой нагрузкой работали ваши системы?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашем опыте работы с микросервисами." },
  { stage: "Background", difficulty: 3, text: "Опишите архитектуру системы, которую вы проектировали." },
  { stage: "Background", difficulty: 3, text: "Как вы взаимодействовали с frontend-разработчиками?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте оптимизации производительности." },
  { stage: "Background", difficulty: 3, text: "Какой был ваш вклад в технические решения в команде?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте менторства." },
  { stage: "Background", difficulty: 4, text: "Как вы принимали архитектурные решения?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте технического лидерства." },
  { stage: "Background", difficulty: 4, text: "Как вы внедряли новые технологии в команде?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте работы с legacy системами." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли техническую стратегию?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте работы с C-level." },
  { stage: "Background", difficulty: 5, text: "Как вы оценивали technical debt?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте построения команды." },
  { stage: "Background", difficulty: 5, text: "Как вы работали с cross-functional проектами?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о самом масштабном проекте, который вы возглавляли." },

  // ========== CORE (70) ==========
  { stage: "Core", difficulty: 1, text: "Что такое REST API?", expectedKeywords: ["REST", "HTTP", "endpoint"] },
  { stage: "Core", difficulty: 1, text: "Объясните HTTP методы: GET, POST, PUT, DELETE." },
  { stage: "Core", difficulty: 1, text: "Что такое JSON?" },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между SQL и NoSQL базами данных." },
  { stage: "Core", difficulty: 1, text: "Что такое индекс в базе данных?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое API." },
  { stage: "Core", difficulty: 1, text: "Что такое авторизация и аутентификация?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое cookie и session." },
  { stage: "Core", difficulty: 1, text: "Что такое middleware?" },
  { stage: "Core", difficulty: 2, text: "Как вы проектируете REST API?", expectedKeywords: ["versioning", "naming", "status codes"] },
  { stage: "Core", difficulty: 2, text: "Объясните разницу между SQL и NoSQL." },
  { stage: "Core", difficulty: 2, text: "Что такое ORM и какие вы использовали?" },
  { stage: "Core", difficulty: 2, text: "Как работает HTTP? Что такое статус коды?" },
  { stage: "Core", difficulty: 2, text: "Объясните JWT токены." },
  { stage: "Core", difficulty: 2, text: "Что такое OAuth 2.0?" },
  { stage: "Core", difficulty: 2, text: "Как работает кеширование?" },
  { stage: "Core", difficulty: 2, text: "Объясните разницу между синхронным и асинхронным кодом." },
  { stage: "Core", difficulty: 2, text: "Что такое WebSocket?" },
  { stage: "Core", difficulty: 2, text: "Как работают очереди сообщений (RabbitMQ, Kafka)?" },
  { stage: "Core", difficulty: 2, text: "Что такое Docker?" },
  { stage: "Core", difficulty: 2, text: "Объясните принципы SOLID." },
  { stage: "Core", difficulty: 2, text: "Что такое DRY, KISS, YAGNI?" },
  { stage: "Core", difficulty: 2, text: "Как работают транзакции в базе данных?" },
  { stage: "Core", difficulty: 3, text: "Как вы проектируете микросервисную архитектуру?", expectedKeywords: ["microservices", "API gateway", "service discovery"] },
  { stage: "Core", difficulty: 3, text: "Объясните CAP теорему." },
  { stage: "Core", difficulty: 3, text: "Что такое eventual consistency?" },
  { stage: "Core", difficulty: 3, text: "Как вы обеспечиваете идемпотентность API?" },
  { stage: "Core", difficulty: 3, text: "Объясните паттерны проектирования: Singleton, Factory, Observer." },
  { stage: "Core", difficulty: 3, text: "Что такое CQRS?" },
  { stage: "Core", difficulty: 3, text: "Объясните Event Sourcing." },
  { stage: "Core", difficulty: 3, text: "Как работает load balancing?" },
  { stage: "Core", difficulty: 3, text: "Что такое rate limiting?" },
  { stage: "Core", difficulty: 3, text: "Объясните circuit breaker pattern." },
  { stage: "Core", difficulty: 3, text: "Что такое distributed tracing?" },
  { stage: "Core", difficulty: 3, text: "Как вы логируете и мониторите приложения?" },
  { stage: "Core", difficulty: 3, text: "Объясните разницу между горизонтальным и вертикальным масштабированием." },
  { stage: "Core", difficulty: 3, text: "Что такое sharding?" },
  { stage: "Core", difficulty: 3, text: "Как работает репликация базы данных?" },
  { stage: "Core", difficulty: 4, text: "Как вы проектируете систему для высокой доступности?", expectedKeywords: ["redundancy", "failover", "health checks"] },
  { stage: "Core", difficulty: 4, text: "Объясните Saga pattern." },
  { stage: "Core", difficulty: 4, text: "Что такое distributed locking?" },
  { stage: "Core", difficulty: 4, text: "Как вы обеспечиваете consistency в распределенных системах?" },
  { stage: "Core", difficulty: 4, text: "Объясните gRPC и Protocol Buffers." },
  { stage: "Core", difficulty: 4, text: "Что такое GraphQL и когда его использовать?" },
  { stage: "Core", difficulty: 4, text: "Как работает Kubernetes?" },
  { stage: "Core", difficulty: 4, text: "Объясните service mesh (Istio, Linkerd)." },
  { stage: "Core", difficulty: 4, text: "Что такое Infrastructure as Code?" },
  { stage: "Core", difficulty: 4, text: "Как вы организуете CI/CD pipeline?" },
  { stage: "Core", difficulty: 5, text: "Как вы проектируете систему для миллионов пользователей?" },
  { stage: "Core", difficulty: 5, text: "Объясните distributed consensus (Raft, Paxos)." },
  { stage: "Core", difficulty: 5, text: "Как работает CDN?" },
  { stage: "Core", difficulty: 5, text: "Что такое blue-green deployment?" },
  { stage: "Core", difficulty: 5, text: "Объясните canary releases." },
  { stage: "Core", difficulty: 5, text: "Как вы обеспечиваете zero-downtime deployment?" },
  { stage: "Core", difficulty: 5, text: "Что такое chaos engineering?" },
  { stage: "Core", difficulty: 5, text: "Как вы проектируете multi-region архитектуру?" },
  { stage: "Core", difficulty: 5, text: "Объясните data mesh." },
  { stage: "Core", difficulty: 5, text: "Что такое event-driven architecture?" },

  // ========== DEEP DIVE (40) ==========
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о сложной технической проблеме, которую вы решали." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы оптимизировали производительность базы данных?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте работы с очередями сообщений." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы обеспечиваете безопасность API?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с кешированием." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы пишете unit тесты?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с интеграционными тестами." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы документируете API?" },
  { stage: "DeepDive", difficulty: 4, text: "Опишите процесс миграции с монолита на микросервисы." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы проводите code review?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте работы с Kubernetes." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы настраиваете мониторинг и alerting?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с database migrations." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с feature flags?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с performance profiling." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете logging в распределенной системе?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с security audits." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с backwards compatibility?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о сложном архитектурном решении, которое вы принимали." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете работу с technical debt?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с incident management." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы проводите post-mortem?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с capacity planning." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы обеспечиваете SLA/SLO?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с disaster recovery." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете error handling?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с API versioning." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с большими файлами (uploads/downloads)?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с WebSockets." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете background jobs?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с search (Elasticsearch)." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с multi-tenancy?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с data pipelines." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете secrets management?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с compliance (GDPR, SOC2)." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с third-party integrations?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с payment systems." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете real-time features?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с geographically distributed systems." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с eventual consistency на практике?" },

  // ========== CASE (25) ==========
  { stage: "Case", difficulty: 2, text: "Как бы вы спроектировали URL shortener?" },
  { stage: "Case", difficulty: 2, text: "Спроектируйте простой REST API для блога." },
  { stage: "Case", difficulty: 2, text: "Как бы вы реализовали rate limiting?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте систему уведомлений (push, email, SMS)." },
  { stage: "Case", difficulty: 3, text: "Как бы вы спроектировали чат-систему?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте систему загрузки и обработки файлов." },
  { stage: "Case", difficulty: 3, text: "Как бы вы спроектировали API для e-commerce?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте систему авторизации с RBAC." },
  { stage: "Case", difficulty: 4, text: "Спроектируйте систему для 1 миллиона одновременных соединений." },
  { stage: "Case", difficulty: 4, text: "Как бы вы спроектировали Twitter?" },
  { stage: "Case", difficulty: 4, text: "Спроектируйте систему доставки для Uber Eats." },
  { stage: "Case", difficulty: 4, text: "Как бы вы спроектировали систему бронирования (Booking.com)?" },
  { stage: "Case", difficulty: 4, text: "Спроектируйте систему платежей." },
  { stage: "Case", difficulty: 4, text: "Как бы вы спроектировали feed (лента новостей)?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте YouTube: загрузка, транскодирование, streaming." },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали Google Docs (collaborative editing)?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте Uber: matching, routing, pricing." },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали distributed search engine?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте систему fraud detection." },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали ad serving system?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте Instagram stories." },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали систему онлайн-игры?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте stock trading platform." },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали Netflix recommendation system?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте distributed key-value store." },

  // ========== DEBUG (15) ==========
  { stage: "Debug", difficulty: 2, text: "API отвечает медленно. Как найдёте причину?" },
  { stage: "Debug", difficulty: 2, text: "Приложение падает с OOM. Как расследуете?" },
  { stage: "Debug", difficulty: 3, text: "Запросы к базе данных стали медленнее. Что делать?" },
  { stage: "Debug", difficulty: 3, text: "Memory leak в production. Как диагностируете?" },
  { stage: "Debug", difficulty: 3, text: "API периодически возвращает 500. Как найдёте причину?" },
  { stage: "Debug", difficulty: 3, text: "Connection pool исчерпан. Как расследуете?" },
  { stage: "Debug", difficulty: 4, text: "Deadlock в базе данных. Как найдёте и исправите?" },
  { stage: "Debug", difficulty: 4, text: "Распределённая транзакция зависла. Что делать?" },
  { stage: "Debug", difficulty: 4, text: "Сервис не отвечает, но процесс работает. Как диагностируете?" },
  { stage: "Debug", difficulty: 4, text: "Данные в кеше и базе рассинхронизировались." },
  { stage: "Debug", difficulty: 5, text: "Произошел data loss. Как восстановите и предотвратите?" },
  { stage: "Debug", difficulty: 5, text: "Cascading failure во всех сервисах. Как остановите?" },
  { stage: "Debug", difficulty: 5, text: "Security breach обнаружен. Ваши действия?" },
  { stage: "Debug", difficulty: 5, text: "Произошла потеря транзакций. Как расследуете?" },
  { stage: "Debug", difficulty: 5, text: "Network partition привел к split brain. Как восстановите?" },

  // ========== WRAPUP (10) ==========
  { stage: "WrapUp", difficulty: 1, text: "Что вам нравится в backend разработке?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие технологии хотите изучить?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы следите за новыми трендами?" },
  { stage: "WrapUp", difficulty: 3, text: "Какой стек технологий предпочитаете и почему?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы относитесь к serverless?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в backend разработке вы считаете важными?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы видите развитие распределённых систем?" },
  { stage: "WrapUp", difficulty: 5, text: "Какой вклад вы хотите внести в индустрию?" },
  { stage: "WrapUp", difficulty: 5, text: "Как изменится backend разработка в будущем?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие технические challenges вас привлекают?" },
];

