// cybersecurity.ts - 200+ вопросов для Cybersecurity Specialist

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const cybersecurityQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (25) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте в кибербезопасности." },
  { stage: "Background", difficulty: 1, text: "Какие сертификации у вас есть?", expectedKeywords: ["CISSP", "CEH", "OSCP", "CompTIA"] },
  { stage: "Background", difficulty: 1, text: "Как вы пришли в кибербезопасность?" },
  { stage: "Background", difficulty: 1, text: "С какими типами атак вы сталкивались?" },
  { stage: "Background", difficulty: 1, text: "Какое у вас образование?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о самом интересном инциденте." },
  { stage: "Background", difficulty: 2, text: "Как была организована security команда?" },
  { stage: "Background", difficulty: 2, text: "Какие инструменты вы использовали?", tags: ["SOC"] },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашем опыте с penetration testing.", tags: ["pentest"] },
  { stage: "Background", difficulty: 2, text: "С какими compliance requirements вы работали?" },
  { stage: "Background", difficulty: 3, text: "Опишите security architecture, которую вы проектировали." },
  { stage: "Background", difficulty: 3, text: "Как вы взаимодействовали с IT и разработчиками?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте incident response." },
  { stage: "Background", difficulty: 3, text: "Какой был ваш вклад в security posture компании?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте менторства." },
  { stage: "Background", difficulty: 4, text: "Как вы определяли security strategy?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте построения SOC.", tags: ["SOC"] },
  { stage: "Background", difficulty: 4, text: "Как вы работали с executive team?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте с security audits." },
  { stage: "Background", difficulty: 5, text: "Как вы строили security program?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте с board reporting." },
  { stage: "Background", difficulty: 5, text: "Как вы оценивали security ROI?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте с регуляторами." },
  { stage: "Background", difficulty: 5, text: "Как вы работали с third-party risk?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о самом критичном инциденте." },

  // ========== CORE (70) ==========
  { stage: "Core", difficulty: 1, text: "Что такое CIA triad?", expectedKeywords: ["confidentiality", "integrity", "availability"] },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между authentication и authorization." },
  { stage: "Core", difficulty: 1, text: "Что такое firewall?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое malware." },
  { stage: "Core", difficulty: 1, text: "Что такое phishing?" },
  { stage: "Core", difficulty: 1, text: "Объясните encryption." },
  { stage: "Core", difficulty: 1, text: "Что такое VPN?" },
  { stage: "Core", difficulty: 1, text: "Объясните SSL/TLS." },
  { stage: "Core", difficulty: 1, text: "Что такое vulnerability?" },
  { stage: "Core", difficulty: 2, text: "Как работает SIEM?", expectedKeywords: ["SIEM", "logs", "correlation"], tags: ["SOC"] },
  { stage: "Core", difficulty: 2, text: "Объясните OWASP Top 10." },
  { stage: "Core", difficulty: 2, text: "Что такое IDS/IPS?" },
  { stage: "Core", difficulty: 2, text: "Объясните SQL injection." },
  { stage: "Core", difficulty: 2, text: "Что такое XSS?" },
  { stage: "Core", difficulty: 2, text: "Объясните CSRF." },
  { stage: "Core", difficulty: 2, text: "Что такое DDoS?" },
  { stage: "Core", difficulty: 2, text: "Объясните ransomware." },
  { stage: "Core", difficulty: 2, text: "Что такое social engineering?" },
  { stage: "Core", difficulty: 2, text: "Объясните privilege escalation." },
  { stage: "Core", difficulty: 2, text: "Что такое lateral movement?" },
  { stage: "Core", difficulty: 2, text: "Объясните network segmentation." },
  { stage: "Core", difficulty: 2, text: "Что такое PKI?" },
  { stage: "Core", difficulty: 2, text: "Объясните hashing vs encryption." },
  { stage: "Core", difficulty: 3, text: "Как вы проводите threat modeling?", expectedKeywords: ["STRIDE", "DREAD", "threat"] },
  { stage: "Core", difficulty: 3, text: "Объясните MITRE ATT&CK framework." },
  { stage: "Core", difficulty: 3, text: "Что такое zero trust architecture?" },
  { stage: "Core", difficulty: 3, text: "Объясните defense in depth." },
  { stage: "Core", difficulty: 3, text: "Как работает EDR?", tags: ["SOC"] },
  { stage: "Core", difficulty: 3, text: "Что такое SOAR?", tags: ["SOC"] },
  { stage: "Core", difficulty: 3, text: "Объясните vulnerability management." },
  { stage: "Core", difficulty: 3, text: "Что такое penetration testing?", tags: ["pentest"] },
  { stage: "Core", difficulty: 3, text: "Объясните red team vs blue team." },
  { stage: "Core", difficulty: 3, text: "Что такое threat intelligence?" },
  { stage: "Core", difficulty: 3, text: "Объясните IoC (Indicators of Compromise)." },
  { stage: "Core", difficulty: 3, text: "Как работает WAF?" },
  { stage: "Core", difficulty: 3, text: "Что такое DLP?", tags: ["DLP"] },
  { stage: "Core", difficulty: 3, text: "Объясните identity management." },
  { stage: "Core", difficulty: 3, text: "Что такое PAM (Privileged Access Management)?" },
  { stage: "Core", difficulty: 4, text: "Как вы проектируете security architecture?", expectedKeywords: ["layers", "controls", "risk"] },
  { stage: "Core", difficulty: 4, text: "Объясните cloud security (AWS, Azure, GCP)." },
  { stage: "Core", difficulty: 4, text: "Что такое container security?" },
  { stage: "Core", difficulty: 4, text: "Объясните DevSecOps." },
  { stage: "Core", difficulty: 4, text: "Как работает SAST/DAST?" },
  { stage: "Core", difficulty: 4, text: "Что такое secure SDLC?" },
  { stage: "Core", difficulty: 4, text: "Объясните API security." },
  { stage: "Core", difficulty: 4, text: "Что такое supply chain security?" },
  { stage: "Core", difficulty: 4, text: "Объясните cryptographic protocols." },
  { stage: "Core", difficulty: 4, text: "Как работает HSM?" },
  { stage: "Core", difficulty: 5, text: "Как вы строите enterprise security program?" },
  { stage: "Core", difficulty: 5, text: "Объясните risk quantification (FAIR)." },
  { stage: "Core", difficulty: 5, text: "Что такое security metrics и KPIs?" },
  { stage: "Core", difficulty: 5, text: "Объясните compliance frameworks (SOC2, ISO27001, PCI-DSS)." },
  { stage: "Core", difficulty: 5, text: "Как работает cyber insurance?" },
  { stage: "Core", difficulty: 5, text: "Объясните privacy regulations (GDPR, CCPA)." },
  { stage: "Core", difficulty: 5, text: "Что такое security governance?" },
  { stage: "Core", difficulty: 5, text: "Объясните third-party risk management." },
  { stage: "Core", difficulty: 5, text: "Как работает security awareness program?" },
  { stage: "Core", difficulty: 5, text: "Объясните business continuity planning." },

  // ========== DEEP DIVE (40) ==========
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о сложном инциденте, который вы расследовали." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы настраивали SIEM rules?", tags: ["SOC"] },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с vulnerability scanning." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы проводите security assessments?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с forensics." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете patch management?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с network security." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы работаете с endpoint security?" },
  { stage: "DeepDive", difficulty: 4, text: "Опишите процесс incident response." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы проводите threat hunting?", tags: ["SOC"] },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с penetration testing.", tags: ["pentest"] },
  { stage: "DeepDive", difficulty: 4, text: "Как вы настраиваете security monitoring?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с cloud security." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с secure code review?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с security awareness training." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете phishing simulations?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с compliance audits." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с vendor security assessments?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о построении SOC.", tags: ["SOC"] },
  { stage: "DeepDive", difficulty: 5, text: "Как вы определяете security roadmap?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с regulatory compliance." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с board reporting?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с M&A security due diligence." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите security culture?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с crisis management." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете access reviews?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с log analysis.", tags: ["SOC"] },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с malware analysis?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с reverse engineering.", tags: ["pentest"] },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете bug bounty program?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с red teaming.", tags: ["pentest"] },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с threat intelligence?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с security automation." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете security architecture review?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с zero trust implementation." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с data protection?", tags: ["DLP"] },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с privacy engineering." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете security metrics?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с security tooling evaluation." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с security budget planning?" },

  // ========== CASE (25) ==========
  { stage: "Case", difficulty: 2, text: "Как бы вы расследовали suspected breach?" },
  { stage: "Case", difficulty: 2, text: "Спроектируйте security для веб-приложения." },
  { stage: "Case", difficulty: 2, text: "Как бы вы настроили firewall rules?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте incident response process." },
  { stage: "Case", difficulty: 3, text: "Как бы вы защитили от ransomware?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте security monitoring.", tags: ["SOC"] },
  { stage: "Case", difficulty: 3, text: "Как бы вы провели penetration test?", tags: ["pentest"] },
  { stage: "Case", difficulty: 3, text: "Спроектируйте access control system." },
  { stage: "Case", difficulty: 4, text: "Спроектируйте security architecture для стартапа." },
  { stage: "Case", difficulty: 4, text: "Как бы вы защитили cloud infrastructure?" },
  { stage: "Case", difficulty: 4, text: "Спроектируйте SOC для средней компании.", tags: ["SOC"] },
  { stage: "Case", difficulty: 4, text: "Как бы вы организовали vulnerability management?" },
  { stage: "Case", difficulty: 4, text: "Спроектируйте DLP solution.", tags: ["DLP"] },
  { stage: "Case", difficulty: 4, text: "Как бы вы защитили от insider threat?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте enterprise security program." },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали zero trust architecture?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте security для финансовой компании." },
  { stage: "Case", difficulty: 5, text: "Как бы вы защитили от APT?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте security для healthcare организации." },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали compliance program?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте security для IoT инфраструктуры." },
  { stage: "Case", difficulty: 5, text: "Как бы вы защитили от supply chain attack?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте security для remote workforce." },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали M&A security integration?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте security metrics dashboard." },

  // ========== DEBUG (15) ==========
  { stage: "Debug", difficulty: 2, text: "Alert в SIEM сработал. Как расследуете?", tags: ["SOC"] },
  { stage: "Debug", difficulty: 2, text: "Пользователь сообщил о подозрительном email. Ваши действия?" },
  { stage: "Debug", difficulty: 3, text: "Обнаружена malware на endpoint. Как реагируете?" },
  { stage: "Debug", difficulty: 3, text: "Suspected data exfiltration. Как расследуете?", tags: ["DLP"] },
  { stage: "Debug", difficulty: 3, text: "Account compromise detected. Ваши действия?" },
  { stage: "Debug", difficulty: 3, text: "DDoS attack in progress. Как реагируете?" },
  { stage: "Debug", difficulty: 4, text: "Ransomware outbreak. Как остановите распространение?" },
  { stage: "Debug", difficulty: 4, text: "Suspicious network traffic detected. Как анализируете?" },
  { stage: "Debug", difficulty: 4, text: "Vulnerability в критичном сервисе. Как приоритизируете?" },
  { stage: "Debug", difficulty: 4, text: "False positive storm в SIEM. Как разберётесь?", tags: ["SOC"] },
  { stage: "Debug", difficulty: 5, text: "Active breach обнаружен. Как координируете response?" },
  { stage: "Debug", difficulty: 5, text: "Insider threat suspected. Как расследуете?" },
  { stage: "Debug", difficulty: 5, text: "Supply chain compromise обнаружен. Ваши действия?" },
  { stage: "Debug", difficulty: 5, text: "Regulatory breach notification required. Как организуете?" },
  { stage: "Debug", difficulty: 5, text: "APT group targeting organization. Как реагируете?" },

  // ========== WRAPUP (10) ==========
  { stage: "WrapUp", difficulty: 1, text: "Что вам нравится в кибербезопасности?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие сертификации планируете получить?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы следите за новыми угрозами?" },
  { stage: "WrapUp", difficulty: 3, text: "Какая область security вас привлекает больше?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы относитесь к bug bounty?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в security вы считаете важными?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы видите развитие AI в кибербезопасности?" },
  { stage: "WrapUp", difficulty: 5, text: "Какой вклад вы хотите внести в индустрию?" },
  { stage: "WrapUp", difficulty: 5, text: "Как изменится кибербезопасность в будущем?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие challenges вас привлекают?" },
];

