// dataAnalyst.ts - 200+ вопросов для Data Analyst

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const dataAnalystQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (30) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте работы с данными.", expectedKeywords: ["анализ", "данные", "отчеты"] },
  { stage: "Background", difficulty: 1, text: "Какие инструменты аналитики вы использовали?", expectedKeywords: ["SQL", "Excel", "Tableau", "Power BI"] },
  { stage: "Background", difficulty: 1, text: "Что привлекает вас в аналитике данных?" },
  { stage: "Background", difficulty: 1, text: "Какое у вас образование? Как оно связано с аналитикой?" },
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем первом проекте в аналитике." },
  { stage: "Background", difficulty: 1, text: "С какими типами данных вы работали?" },
  { stage: "Background", difficulty: 1, text: "Какой язык программирования вы используете для анализа?" },
  { stage: "Background", difficulty: 2, text: "В каких командах и доменах вы работали аналитиком?" },
  { stage: "Background", difficulty: 2, text: "Какой аналитический проект вы считаете наиболее значимым?" },
  { stage: "Background", difficulty: 2, text: "Как вы пришли в аналитику данных?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о типичном рабочем дне аналитика в вашей компании." },
  { stage: "Background", difficulty: 2, text: "С какими стейкхолдерами вы взаимодействовали?" },
  { stage: "Background", difficulty: 2, text: "Какой был размер команды аналитиков?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о самом сложном дашборде, который вы создавали." },
  { stage: "Background", difficulty: 2, text: "Какие BI-инструменты вы предпочитаете и почему?" },
  { stage: "Background", difficulty: 3, text: "Как была организована ваша работа с продуктовой командой?" },
  { stage: "Background", difficulty: 3, text: "Какие метрики вы отслеживали и почему именно их?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о случае, когда ваш анализ повлиял на бизнес-решение." },
  { stage: "Background", difficulty: 3, text: "Как вы организовывали процесс сбора требований от заказчиков?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте менторства junior аналитиков." },
  { stage: "Background", difficulty: 3, text: "Как вы документировали свои аналитические процессы?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте построения аналитической культуры в команде." },
  { stage: "Background", difficulty: 4, text: "Как вы внедряли новые инструменты аналитики в компании?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о опыте работы с data warehouse." },
  { stage: "Background", difficulty: 4, text: "Как вы организовывали работу с несколькими источниками данных?" },
  { stage: "Background", difficulty: 5, text: "Как вы выстраивали data governance и качество данных?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте построения self-service аналитики." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли стратегию развития аналитики в компании?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте работы с executive-level отчетностью." },
  { stage: "Background", difficulty: 5, text: "Как вы оценивали ROI аналитических инициатив?" },

  // ========== CORE (60) ==========
  { stage: "Core", difficulty: 1, text: "Какими инструментами для отчётов и дэшбордов вы пользуетесь?", expectedKeywords: ["Tableau", "Power BI", "Looker"] },
  { stage: "Core", difficulty: 1, text: "Что такое конверсия и как её считать?", expectedKeywords: ["конверсия", "воронка", "процент"] },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между метрикой и KPI.", expectedKeywords: ["метрика", "KPI", "цель"] },
  { stage: "Core", difficulty: 1, text: "Что такое среднее, медиана и мода?", expectedKeywords: ["среднее", "медиана", "мода"] },
  { stage: "Core", difficulty: 1, text: "Как вы фильтруете данные в Excel?" },
  { stage: "Core", difficulty: 1, text: "Что такое pivot table и зачем она нужна?" },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между COUNT и COUNT DISTINCT." },
  { stage: "Core", difficulty: 1, text: "Что такое NULL в базе данных?" },
  { stage: "Core", difficulty: 1, text: "Как вы создаете графики и визуализации?" },
  { stage: "Core", difficulty: 1, text: "Что такое выборка и генеральная совокупность?" },
  { stage: "Core", difficulty: 2, text: "Как вы формулируете гипотезу и проверяете её на данных?", expectedKeywords: ["гипотеза", "тест", "статистика"] },
  { stage: "Core", difficulty: 2, text: "Опишите SQL-запрос для анализа поведения пользователей." },
  { stage: "Core", difficulty: 2, text: "Что такое retention и как его считать?", expectedKeywords: ["retention", "удержание", "когорта"] },
  { stage: "Core", difficulty: 2, text: "Как вы работаете с воронками продаж?", expectedKeywords: ["воронка", "конверсия", "этапы"] },
  { stage: "Core", difficulty: 2, text: "Что такое DAU, WAU, MAU?" },
  { stage: "Core", difficulty: 2, text: "Как посчитать churn rate?" },
  { stage: "Core", difficulty: 2, text: "Что такое ARPU и ARPPU?" },
  { stage: "Core", difficulty: 2, text: "Объясните разницу между correlation и causation." },
  { stage: "Core", difficulty: 2, text: "Как вы обрабатываете выбросы в данных?" },
  { stage: "Core", difficulty: 2, text: "Что такое нормальное распределение?" },
  { stage: "Core", difficulty: 2, text: "Как вы визуализируете временные ряды?" },
  { stage: "Core", difficulty: 2, text: "Что такое moving average и зачем он нужен?" },
  { stage: "Core", difficulty: 2, text: "Как вы определяете сезонность в данных?" },
  { stage: "Core", difficulty: 2, text: "Что такое percentile и quartile?" },
  { stage: "Core", difficulty: 2, text: "Как вы работаете с категориальными переменными?" },
  { stage: "Core", difficulty: 3, text: "Как определяете целевую метрику для продукта или фичи?", expectedKeywords: ["north star", "метрика", "цель"] },
  { stage: "Core", difficulty: 3, text: "Как работаете с сессиями, событиями и user_id?" },
  { stage: "Core", difficulty: 3, text: "Расскажите о вашем подходе к A/B тестированию.", expectedKeywords: ["A/B", "гипотеза", "значимость"] },
  { stage: "Core", difficulty: 3, text: "Как вы считаете статистическую значимость?", expectedKeywords: ["p-value", "confidence"] },
  { stage: "Core", difficulty: 3, text: "Что такое когортный анализ и когда его использовать?", expectedKeywords: ["когорта", "retention", "LTV"] },
  { stage: "Core", difficulty: 3, text: "Как вы определяете sample size для A/B теста?" },
  { stage: "Core", difficulty: 3, text: "Что такое p-value и как его интерпретировать?" },
  { stage: "Core", difficulty: 3, text: "Объясните разницу между Type I и Type II errors." },
  { stage: "Core", difficulty: 3, text: "Как вы работаете с multiple comparisons problem?" },
  { stage: "Core", difficulty: 3, text: "Что такое confidence interval?" },
  { stage: "Core", difficulty: 3, text: "Как вы считаете LTV?", expectedKeywords: ["LTV", "lifetime value", "прогноз"] },
  { stage: "Core", difficulty: 3, text: "Что такое CAC и как его оптимизировать?" },
  { stage: "Core", difficulty: 3, text: "Как вы строите unit-экономику?" },
  { stage: "Core", difficulty: 3, text: "Что такое payback period?" },
  { stage: "Core", difficulty: 3, text: "Как вы работаете с attribution?" },
  { stage: "Core", difficulty: 3, text: "Объясните разницу между last-click и first-click attribution." },
  { stage: "Core", difficulty: 3, text: "Как вы анализируете user journey?" },
  { stage: "Core", difficulty: 3, text: "Что такое RFM-анализ?" },
  { stage: "Core", difficulty: 3, text: "Как вы сегментируете пользователей?" },
  { stage: "Core", difficulty: 4, text: "Как вы проектируете систему метрик для нового продукта?", expectedKeywords: ["north star", "supporting metrics"] },
  { stage: "Core", difficulty: 4, text: "Расскажите о вашем опыте с attribution modeling." },
  { stage: "Core", difficulty: 4, text: "Как вы работаете с Simpson's paradox?" },
  { stage: "Core", difficulty: 4, text: "Что такое Bayesian vs Frequentist подход в статистике?" },
  { stage: "Core", difficulty: 4, text: "Как вы настраиваете alerting для метрик?" },
  { stage: "Core", difficulty: 4, text: "Расскажите о вашем опыте с experimentation platform." },
  { stage: "Core", difficulty: 4, text: "Как вы работаете с network effects в метриках?" },
  { stage: "Core", difficulty: 4, text: "Что такое novelty effect в A/B тестах?" },
  { stage: "Core", difficulty: 4, text: "Как вы проводите post-hoc анализ?" },
  { stage: "Core", difficulty: 5, text: "Как вы строите predictive analytics для бизнес-метрик?" },
  { stage: "Core", difficulty: 5, text: "Расскажите о вашем опыте с causal inference." },
  { stage: "Core", difficulty: 5, text: "Как вы работаете с instrumental variables?" },
  { stage: "Core", difficulty: 5, text: "Что такое regression discontinuity design?" },
  { stage: "Core", difficulty: 5, text: "Как вы применяете difference-in-differences?" },
  { stage: "Core", difficulty: 5, text: "Расскажите о propensity score matching." },

  // ========== SQL (40) ==========
  { stage: "SQL", difficulty: 1, text: "Напишите запрос для выборки всех пользователей из таблицы users." },
  { stage: "SQL", difficulty: 1, text: "Как отфильтровать данные по дате?" },
  { stage: "SQL", difficulty: 1, text: "Объясните разницу между WHERE и HAVING." },
  { stage: "SQL", difficulty: 1, text: "Что делает GROUP BY?" },
  { stage: "SQL", difficulty: 1, text: "Как посчитать количество записей в таблице?" },
  { stage: "SQL", difficulty: 1, text: "Как отсортировать результаты запроса?" },
  { stage: "SQL", difficulty: 1, text: "Что делает LIMIT?" },
  { stage: "SQL", difficulty: 1, text: "Как выбрать уникальные значения?" },
  { stage: "SQL", difficulty: 2, text: "Объясните разницу между INNER JOIN, LEFT JOIN и FULL OUTER JOIN." },
  { stage: "SQL", difficulty: 2, text: "Как работает GROUP BY? Когда использовать HAVING вместо WHERE?" },
  { stage: "SQL", difficulty: 2, text: "Напишите запрос для расчета конверсии по воронке." },
  { stage: "SQL", difficulty: 2, text: "Как объединить данные из двух таблиц?" },
  { stage: "SQL", difficulty: 2, text: "Что такое подзапрос и когда его использовать?" },
  { stage: "SQL", difficulty: 2, text: "Как посчитать уникальных пользователей за день?" },
  { stage: "SQL", difficulty: 2, text: "Напишите запрос с использованием CASE WHEN." },
  { stage: "SQL", difficulty: 2, text: "Как работает COALESCE?" },
  { stage: "SQL", difficulty: 2, text: "Что такое UNION и UNION ALL?" },
  { stage: "SQL", difficulty: 2, text: "Как посчитать среднее значение по группам?" },
  { stage: "SQL", difficulty: 3, text: "Как вы используете оконные функции для накопительных метрик?", expectedKeywords: ["window function", "SUM OVER"] },
  { stage: "SQL", difficulty: 3, text: "Объясните разницу между ROW_NUMBER(), RANK() и DENSE_RANK()." },
  { stage: "SQL", difficulty: 3, text: "Напишите запрос для когортного анализа: retention по месяцу регистрации." },
  { stage: "SQL", difficulty: 3, text: "Как посчитать LTV пользователя с помощью SQL?" },
  { stage: "SQL", difficulty: 3, text: "Напишите запрос для расчета moving average." },
  { stage: "SQL", difficulty: 3, text: "Как найти пользователей, сделавших покупку в первый день?" },
  { stage: "SQL", difficulty: 3, text: "Напишите запрос с использованием LAG и LEAD." },
  { stage: "SQL", difficulty: 3, text: "Как построить воронку регистрации в SQL?" },
  { stage: "SQL", difficulty: 3, text: "Напишите запрос для расчета retention Day 1, Day 7, Day 30." },
  { stage: "SQL", difficulty: 3, text: "Как найти топ-10 пользователей по сумме покупок?" },
  { stage: "SQL", difficulty: 4, text: "Как написать запрос для поиска цепочек событий (sessionization)?" },
  { stage: "SQL", difficulty: 4, text: "Напишите запрос для определения первой и последней покупки каждого пользователя." },
  { stage: "SQL", difficulty: 4, text: "Как оптимизировать медленный запрос?" },
  { stage: "SQL", difficulty: 4, text: "Напишите запрос для расчета churn по когортам." },
  { stage: "SQL", difficulty: 4, text: "Как работать с JSON в SQL?" },
  { stage: "SQL", difficulty: 4, text: "Напишите рекурсивный CTE." },
  { stage: "SQL", difficulty: 4, text: "Как найти gaps в данных (пропущенные дни)?" },
  { stage: "SQL", difficulty: 5, text: "Как реализовать RFM-сегментацию в SQL?" },
  { stage: "SQL", difficulty: 5, text: "Напишите запрос для attribution modeling." },
  { stage: "SQL", difficulty: 5, text: "Как оптимизировать запрос с несколькими JOIN?" },
  { stage: "SQL", difficulty: 5, text: "Напишите запрос для построения user journey." },
  { stage: "SQL", difficulty: 5, text: "Как работать с партиционированными таблицами?" },

  // ========== DEEP DIVE (35) ==========
  { stage: "DeepDive", difficulty: 2, text: "Расскажите о вашем процессе создания дашборда от и до." },
  { stage: "DeepDive", difficulty: 2, text: "Как вы презентуете результаты анализа стейкхолдерам?" },
  { stage: "DeepDive", difficulty: 3, text: "Опишите кейс, когда ваши выводы повлияли на roadmap продукта." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы анализируете причины падения метрики?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о сложном дашборде, который вы создавали." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы проводите root cause analysis?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о случае, когда данные были неполными." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы автоматизировали рутинные отчеты?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте работы с data quality issues." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы определяете приоритеты аналитических задач?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о сложном SQL-запросе, который вы оптимизировали." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы подходите к сегментации пользователей?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с causal inference." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с несколькими источниками данных?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о случае, когда A/B тест показал неожиданные результаты." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы документируете свои аналитические процессы?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте построения data pipelines." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с real-time данными?" },
  { stage: "DeepDive", difficulty: 5, text: "Приведите пример спора со стейкхолдерами на основе данных." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите self-service аналитику для команды?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с experimentation platform." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы определяете метрики для нового продукта с нуля?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте работы с ML-моделями." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы масштабируете аналитические процессы?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с data governance." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы объясняете сложные концепции non-technical аудитории?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте работы с Tableau/Power BI." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы настраиваете alerts для критических метрик?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем подходе к data storytelling." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с unstructured data?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с Python для аналитики." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы валидируете данные перед анализом?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте построения metrics framework." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете работу с technical debt в аналитике?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с data democratization." },

  // ========== CASE (25) ==========
  { stage: "Case", difficulty: 2, text: "Как бы вы посчитали конверсию по воронке регистрации?" },
  { stage: "Case", difficulty: 2, text: "Менеджер просит отчёт по продажам за месяц. Что включите?" },
  { stage: "Case", difficulty: 2, text: "Как бы вы измерили успех email-рассылки?" },
  { stage: "Case", difficulty: 2, text: "Вам нужно понять, почему упали продажи. С чего начнете?" },
  { stage: "Case", difficulty: 3, text: "Конверсия упала на 20%. С чего начнёте разбор?" },
  { stage: "Case", difficulty: 3, text: "Как построите воронку: просмотр → корзина → покупка?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы оценили эффект от новой фичи?" },
  { stage: "Case", difficulty: 3, text: "Продакт просит посчитать LTV. Как подойдёте?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы настроили A/B тест для новой страницы checkout?" },
  { stage: "Case", difficulty: 3, text: "Retention упал. Как найдете причину?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы измерили эффективность маркетинговой кампании?" },
  { stage: "Case", difficulty: 3, text: "Вам нужно сравнить два варианта UI. Как организуете эксперимент?" },
  { stage: "Case", difficulty: 4, text: "Как спроектировать дэшборд для CPO о здоровье продукта?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы построили систему раннего предупреждения о проблемах?" },
  { stage: "Case", difficulty: 4, text: "A/B тест показал противоречивые результаты. Как разберётесь?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы оценили каннибализацию между продуктами?" },
  { stage: "Case", difficulty: 4, text: "Нужно определить optimal pricing. Как подойдете?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы построили propensity model?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали data democratization в компании?" },
  { stage: "Case", difficulty: 5, text: "Нужно оценить ROI от аналитической команды. Как подойдёте?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали experimentation platform?" },
  { stage: "Case", difficulty: 5, text: "Вам нужно построить real-time dashboard для trading." },
  { stage: "Case", difficulty: 5, text: "Как бы вы оценили long-term impact фичи?" },
  { stage: "Case", difficulty: 5, text: "Нужно построить attribution model. Какой подход выберете?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы определили optimal notification frequency?" },

  // ========== DEBUG (10) ==========
  { stage: "Debug", difficulty: 2, text: "Цифры в отчёте не сходятся. Как будете искать ошибку?" },
  { stage: "Debug", difficulty: 2, text: "Дашборд показывает странные значения. Ваши действия?" },
  { stage: "Debug", difficulty: 3, text: "Видите скачок метрики, но подозреваете артефакт данных." },
  { stage: "Debug", difficulty: 3, text: "A/B тест показывает статистически значимый результат, но вы сомневаетесь." },
  { stage: "Debug", difficulty: 3, text: "Retention внезапно вырос на 50%. Это реальность или баг?" },
  { stage: "Debug", difficulty: 4, text: "Обнаружили ошибку в трекинге событий. Как оцените ущерб?" },
  { stage: "Debug", difficulty: 4, text: "Данные из разных источников противоречат друг другу." },
  { stage: "Debug", difficulty: 4, text: "Запрос работает медленно на production. Как оптимизируете?" },
  { stage: "Debug", difficulty: 5, text: "После миграции данных метрики изменились. Как валидируете?" },
  { stage: "Debug", difficulty: 5, text: "Исторические данные оказались некорректными." },

  // ========== WRAPUP (10) ==========
  { stage: "WrapUp", difficulty: 1, text: "Что вам больше всего нравится в аналитике?" },
  { stage: "WrapUp", difficulty: 2, text: "Какую роль предпочитаете: исследовательскую или операционную?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие навыки хотите развить в ближайший год?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы следите за новыми трендами в аналитике?" },
  { stage: "WrapUp", difficulty: 3, text: "В каких доменах хотите развиваться как аналитик?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы относитесь к Python/R для аналитики?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в аналитике данных вы считаете важными?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы относитесь к ML/AI в аналитике?" },
  { stage: "WrapUp", difficulty: 5, text: "Как вы видите развитие data-driven культуры?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие challenges в аналитике вас привлекают больше всего?" },
];

