// dataScientist.ts - 200+ вопросов для Data Scientist / ML Engineer

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const dataScientistQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (25) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте работы с данными и машинным обучением." },
  { stage: "Background", difficulty: 1, text: "Какое образование у вас? Какие курсы проходили?" },
  { stage: "Background", difficulty: 1, text: "Какие проекты по Data Science вы делали?" },
  { stage: "Background", difficulty: 1, text: "С какими типами задач ML вы работали?" },
  { stage: "Background", difficulty: 1, text: "Какой язык программирования вы используете для ML?" },
  { stage: "Background", difficulty: 2, text: "Какой проект по анализу данных вы считаете наиболее успешным?" },
  { stage: "Background", difficulty: 2, text: "С какими типами задач ML вы работали: классификация, регрессия, кластеризация?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашем опыте участия в Kaggle." },
  { stage: "Background", difficulty: 2, text: "Какие ML-фреймворки вы использовали?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашем опыте работы с big data." },
  { stage: "Background", difficulty: 3, text: "Опишите типичный end-to-end проект Data Science." },
  { stage: "Background", difficulty: 3, text: "Как была организована команда Data Science в вашей компании?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте работы с production ML." },
  { stage: "Background", difficulty: 3, text: "Как вы взаимодействовали с инженерами и продактами?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о самом сложном ML-проекте." },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте внедрения ML-моделей в продакшен." },
  { stage: "Background", difficulty: 4, text: "Как вы менторили junior data scientists?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте работы с MLOps." },
  { stage: "Background", difficulty: 4, text: "Как вы определяли roadmap для ML-проектов?" },
  { stage: "Background", difficulty: 5, text: "Как вы выстраивали DS-процессы в команде или компании?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте работы с C-level по ML-инициативам." },
  { stage: "Background", difficulty: 5, text: "Как вы оценивали business impact ваших моделей?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте построения ML-платформы." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли стратегию ML в компании?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте работы с регуляторами (GDPR, etc)." },

  // ========== CORE (70) ==========
  { stage: "Core", difficulty: 1, text: "Какие библиотеки Python для анализа данных вы используете?", expectedKeywords: ["pandas", "numpy", "sklearn"] },
  { stage: "Core", difficulty: 1, text: "Что такое pandas DataFrame? Какие операции вы знаете?" },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между supervised и unsupervised learning.", expectedKeywords: ["supervised", "unsupervised", "labeled"] },
  { stage: "Core", difficulty: 1, text: "Что такое линейная регрессия?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое classification." },
  { stage: "Core", difficulty: 1, text: "Что такое train/test split?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое accuracy." },
  { stage: "Core", difficulty: 1, text: "Что такое feature и target?" },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между regression и classification." },
  { stage: "Core", difficulty: 2, text: "Объясните разницу между overfitting и underfitting.", expectedKeywords: ["overfitting", "underfitting", "bias", "variance"] },
  { stage: "Core", difficulty: 2, text: "Как вы делите выборку на train/validation/test?" },
  { stage: "Core", difficulty: 2, text: "Что такое cross-validation и зачем она нужна?", expectedKeywords: ["cross-validation", "k-fold"] },
  { stage: "Core", difficulty: 2, text: "Объясните разницу между precision и recall.", expectedKeywords: ["precision", "recall", "F1"] },
  { stage: "Core", difficulty: 2, text: "Что такое confusion matrix?" },
  { stage: "Core", difficulty: 2, text: "Объясните ROC curve и AUC." },
  { stage: "Core", difficulty: 2, text: "Что такое decision tree?" },
  { stage: "Core", difficulty: 2, text: "Объясните random forest." },
  { stage: "Core", difficulty: 2, text: "Что такое logistic regression?" },
  { stage: "Core", difficulty: 2, text: "Объясните K-means clustering." },
  { stage: "Core", difficulty: 2, text: "Что такое PCA и зачем он нужен?" },
  { stage: "Core", difficulty: 2, text: "Объясните feature scaling." },
  { stage: "Core", difficulty: 2, text: "Что такое one-hot encoding?" },
  { stage: "Core", difficulty: 2, text: "Как вы обрабатываете пропуски в данных?" },
  { stage: "Core", difficulty: 3, text: "Какие метрики используете для классификации? Когда какую?", expectedKeywords: ["accuracy", "precision", "recall", "F1", "AUC"] },
  { stage: "Core", difficulty: 3, text: "Как вы боретесь с дисбалансом классов?", expectedKeywords: ["oversampling", "undersampling", "SMOTE"] },
  { stage: "Core", difficulty: 3, text: "Объясните как работает gradient boosting (XGBoost, LightGBM).", expectedKeywords: ["gradient boosting", "ensemble"] },
  { stage: "Core", difficulty: 3, text: "Что такое regularization? Зачем нужны L1 и L2?", expectedKeywords: ["regularization", "L1", "L2", "Lasso", "Ridge"] },
  { stage: "Core", difficulty: 3, text: "Объясните bias-variance tradeoff." },
  { stage: "Core", difficulty: 3, text: "Что такое hyperparameter tuning?" },
  { stage: "Core", difficulty: 3, text: "Объясните Grid Search vs Random Search." },
  { stage: "Core", difficulty: 3, text: "Что такое bagging и boosting?" },
  { stage: "Core", difficulty: 3, text: "Объясните SVM и kernel trick." },
  { stage: "Core", difficulty: 3, text: "Что такое neural network?" },
  { stage: "Core", difficulty: 3, text: "Объясните backpropagation." },
  { stage: "Core", difficulty: 3, text: "Что такое activation function?" },
  { stage: "Core", difficulty: 3, text: "Объясните dropout и batch normalization." },
  { stage: "Core", difficulty: 3, text: "Что такое learning rate?" },
  { stage: "Core", difficulty: 3, text: "Объясните optimizer (SGD, Adam)." },
  { stage: "Core", difficulty: 3, text: "Что такое early stopping?" },
  { stage: "Core", difficulty: 4, text: "Как вы подходите к feature selection?", expectedKeywords: ["feature importance", "correlation"] },
  { stage: "Core", difficulty: 4, text: "Расскажите о вашем опыте с deep learning." },
  { stage: "Core", difficulty: 4, text: "Что такое CNN и для чего используется?" },
  { stage: "Core", difficulty: 4, text: "Объясните RNN и LSTM." },
  { stage: "Core", difficulty: 4, text: "Что такое attention mechanism?" },
  { stage: "Core", difficulty: 4, text: "Объясните transfer learning." },
  { stage: "Core", difficulty: 4, text: "Что такое embedding?" },
  { stage: "Core", difficulty: 4, text: "Объясните Word2Vec и BERT." },
  { stage: "Core", difficulty: 4, text: "Что такое autoencoder?" },
  { stage: "Core", difficulty: 4, text: "Объясните GAN." },
  { stage: "Core", difficulty: 4, text: "Что такое reinforcement learning?" },
  { stage: "Core", difficulty: 4, text: "Объясните time series forecasting methods." },
  { stage: "Core", difficulty: 4, text: "Что такое ARIMA?" },
  { stage: "Core", difficulty: 4, text: "Объясните Prophet." },
  { stage: "Core", difficulty: 5, text: "Как вы проектируете ML-системы для высоких нагрузок?" },
  { stage: "Core", difficulty: 5, text: "Объясните model serving patterns." },
  { stage: "Core", difficulty: 5, text: "Что такое feature store?" },
  { stage: "Core", difficulty: 5, text: "Объясните online vs offline inference." },
  { stage: "Core", difficulty: 5, text: "Как вы организуете model versioning?" },
  { stage: "Core", difficulty: 5, text: "Объясните A/B testing для ML моделей." },
  { stage: "Core", difficulty: 5, text: "Что такое shadow deployment?" },
  { stage: "Core", difficulty: 5, text: "Объясните canary deployment для моделей." },
  { stage: "Core", difficulty: 5, text: "Как вы мониторите модели в production?" },
  { stage: "Core", difficulty: 5, text: "Объясните concept drift и data drift." },
  { stage: "Core", difficulty: 5, text: "Что такое model explainability?" },
  { stage: "Core", difficulty: 5, text: "Объясните SHAP values." },
  { stage: "Core", difficulty: 5, text: "Что такое LIME?" },
  { stage: "Core", difficulty: 5, text: "Объясните fairness в ML." },
  { stage: "Core", difficulty: 5, text: "Как вы работаете с ML ethics?" },
  { stage: "Core", difficulty: 5, text: "Что такое Transformer architecture?" },

  // ========== DEEP DIVE (40) ==========
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о случае, когда модель провалилась в проде." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы проводите EDA (exploratory data analysis)?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем подходе к feature engineering." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы работаете с категориальными фичами?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с imbalanced datasets." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы выбираете baseline model?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем процессе model selection." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы документируете эксперименты?" },
  { stage: "DeepDive", difficulty: 4, text: "Опишите ваш подход к feature engineering в реальном проекте." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете эксперименты: логирование, сравнение моделей?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с AutoML." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с временными рядами?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с NLP." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с изображениями (Computer Vision)?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с recommender systems." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с graph data?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с anomaly detection." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы подходите к multi-task learning?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с online learning." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с streaming data?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о сложном кейсе, где меняли постановку задачи." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите reproducible ML pipelines?" },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете ML platform?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с distributed training." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с model compression?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с edge deployment." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы подходите к ML system design?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с causal ML." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с multi-modal data?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте работы с Spark MLlib." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы работаете с большими датасетами?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с PyTorch vs TensorFlow." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете code review для ML кода?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с Kubeflow/MLflow." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с model registry?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с LLM fine-tuning." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с RAG?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с prompt engineering." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы оцениваете LLM outputs?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с vector databases." },

  // ========== CASE (30) ==========
  { stage: "Case", difficulty: 2, text: "Как бы вы подошли к задаче предсказания цены квартиры?" },
  { stage: "Case", difficulty: 2, text: "Какую модель выберете для бинарной классификации и почему?" },
  { stage: "Case", difficulty: 2, text: "Как бы вы предсказали, кликнет ли пользователь на рекламу?" },
  { stage: "Case", difficulty: 2, text: "Как бы вы определили спам в email?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы подошли к задаче предсказания оттока клиентов?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы построили рекомендательную систему?" },
  { stage: "Case", difficulty: 3, text: "У вас 1000 фичей. Как выберете наиболее важные?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы предсказали время доставки заказа?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы определили fake reviews?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы построили систему sentiment analysis?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы предсказали demand для товара?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы сегментировали пользователей для маркетинга?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы построили систему A/B-тестирования для ML-модели?" },
  { stage: "Case", difficulty: 4, text: "Как извлечь фичи из лог-данных для предсказания конверсии?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы спроектировали fraud detection систему?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы построили search ranking model?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы предсказали lifetime value клиента?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы построили систему dynamic pricing?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы определили anomalies в транзакциях?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы построили content moderation system?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили real-time ML inference pipeline?" },
  { stage: "Case", difficulty: 5, text: "Как организовать continuous training для модели?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали ML систему для self-driving cars?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили систему для medical diagnosis?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали ML для 1B+ users?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили multi-language NLP system?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы спроектировали recommendation system для YouTube?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили predictive maintenance system?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали ML для финансовых прогнозов?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили conversational AI system?" },

  // ========== DEBUG (20) ==========
  { stage: "Debug", difficulty: 2, text: "Модель показывает 99% accuracy. Это хорошо или плохо?" },
  { stage: "Debug", difficulty: 2, text: "Training loss падает, но validation loss растет. Что это значит?" },
  { stage: "Debug", difficulty: 2, text: "Модель предсказывает один класс для всех примеров." },
  { stage: "Debug", difficulty: 3, text: "Модель внезапно стала хуже работать. Какие шаги?" },
  { stage: "Debug", difficulty: 3, text: "Модель хорошо работает на train, плохо на test." },
  { stage: "Debug", difficulty: 3, text: "Cross-validation дает разные результаты на разных folds." },
  { stage: "Debug", difficulty: 3, text: "Модель работает медленно на inference. Как оптимизировать?" },
  { stage: "Debug", difficulty: 3, text: "Feature importance показывает странные результаты." },
  { stage: "Debug", difficulty: 3, text: "Модель работает хорошо в ноутбуке, плохо в production." },
  { stage: "Debug", difficulty: 4, text: "Вы заметили data drift в проде. Как диагностируете?" },
  { stage: "Debug", difficulty: 4, text: "Модель деградирует со временем. Как настроите мониторинг?" },
  { stage: "Debug", difficulty: 4, text: "A/B тест ML-модели показал негативные результаты." },
  { stage: "Debug", difficulty: 4, text: "Модель показывает bias против определенной группы." },
  { stage: "Debug", difficulty: 4, text: "Training стал нестабильным. Как дебажить?" },
  { stage: "Debug", difficulty: 4, text: "Модель выдает разные результаты при повторных запусках." },
  { stage: "Debug", difficulty: 5, text: "Как подходите к explainability модели для бизнеса?" },
  { stage: "Debug", difficulty: 5, text: "Обнаружили data leakage. Как исправить?" },
  { stage: "Debug", difficulty: 5, text: "Модель в production потребляет много ресурсов." },
  { stage: "Debug", difficulty: 5, text: "Обнаружили adversarial examples. Как защитить модель?" },
  { stage: "Debug", difficulty: 5, text: "Модель делает критические ошибки в редких случаях." },

  // ========== WRAPUP (15) ==========
  { stage: "WrapUp", difficulty: 1, text: "Какие направления в Data Science вам интересны?" },
  { stage: "WrapUp", difficulty: 2, text: "Чему хотите научиться в ближайший год?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие papers вы читали недавно?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы следите за новостями в ML?" },
  { stage: "WrapUp", difficulty: 3, text: "Какие компромиссы готовы делать между качеством и сложностью?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы относитесь к AutoML?" },
  { stage: "WrapUp", difficulty: 3, text: "Какой баланс между research и production вы предпочитаете?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в ML вы считаете важными?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы видите влияние LLM на Data Science?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие ethical challenges в ML вас волнуют?" },
  { stage: "WrapUp", difficulty: 4, text: "Изменится ли роль Data Scientist с развитием AI?" },
  { stage: "WrapUp", difficulty: 5, text: "Какой вклад вы хотите внести в область ML?" },
  { stage: "WrapUp", difficulty: 5, text: "Как вы видите будущее AI через 5-10 лет?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие нерешенные проблемы в ML вас привлекают?" },
  { stage: "WrapUp", difficulty: 5, text: "Как вы балансируете innovation vs pragmatism?" },
];

