// devops.ts - 200+ вопросов для DevOps / SRE Engineer

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const devopsQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (25) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте в DevOps/SRE." },
  { stage: "Background", difficulty: 1, text: "Какие инструменты вы использовали?", expectedKeywords: ["Docker", "Kubernetes", "Jenkins", "Terraform"] },
  { stage: "Background", difficulty: 1, text: "Как вы пришли в DevOps?" },
  { stage: "Background", difficulty: 1, text: "С какими облачными провайдерами вы работали?" },
  { stage: "Background", difficulty: 1, text: "Какое у вас образование?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о самом интересном проекте." },
  { stage: "Background", difficulty: 2, text: "Как была организована команда?" },
  { stage: "Background", difficulty: 2, text: "С какой нагрузкой работали ваши системы?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашем опыте с on-call." },
  { stage: "Background", difficulty: 2, text: "Какие методологии вы применяете?" },
  { stage: "Background", difficulty: 3, text: "Опишите инфраструктуру, которую вы создавали." },
  { stage: "Background", difficulty: 3, text: "Как вы взаимодействовали с разработчиками?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте с incident management." },
  { stage: "Background", difficulty: 3, text: "Какой был ваш вклад в reliability?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте менторства." },
  { stage: "Background", difficulty: 4, text: "Как вы определяли SLO/SLA?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте построения platform team." },
  { stage: "Background", difficulty: 4, text: "Как вы внедряли новые практики?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о миграции на новую инфраструктуру." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли инфраструктурную стратегию?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте с cost optimization." },
  { stage: "Background", difficulty: 5, text: "Как вы работали с compliance requirements?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о построении disaster recovery." },
  { stage: "Background", difficulty: 5, text: "Как вы масштабировали инфраструктуру для роста?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о самом критичном инциденте, который вы разрешали." },

  // ========== CORE (70) ==========
  { stage: "Core", difficulty: 1, text: "Что такое Docker?", expectedKeywords: ["контейнер", "image", "container"] },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между VM и контейнером." },
  { stage: "Core", difficulty: 1, text: "Что такое CI/CD?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое deployment." },
  { stage: "Core", difficulty: 1, text: "Что такое git?" },
  { stage: "Core", difficulty: 1, text: "Объясните базовые команды Linux." },
  { stage: "Core", difficulty: 1, text: "Что такое SSH?" },
  { stage: "Core", difficulty: 1, text: "Объясните DNS." },
  { stage: "Core", difficulty: 1, text: "Что такое load balancer?" },
  { stage: "Core", difficulty: 2, text: "Как работает Kubernetes?", expectedKeywords: ["pod", "node", "service", "deployment"] },
  { stage: "Core", difficulty: 2, text: "Объясните разницу между Deployment, StatefulSet, DaemonSet." },
  { stage: "Core", difficulty: 2, text: "Что такое Infrastructure as Code?", expectedKeywords: ["Terraform", "CloudFormation", "Pulumi"] },
  { stage: "Core", difficulty: 2, text: "Объясните networking в Docker." },
  { stage: "Core", difficulty: 2, text: "Что такое Helm?" },
  { stage: "Core", difficulty: 2, text: "Объясните ConfigMap и Secret в Kubernetes." },
  { stage: "Core", difficulty: 2, text: "Как работает Ingress?" },
  { stage: "Core", difficulty: 2, text: "Что такое Prometheus и Grafana?" },
  { stage: "Core", difficulty: 2, text: "Объясните logging (ELK stack)." },
  { stage: "Core", difficulty: 2, text: "Что такое reverse proxy?" },
  { stage: "Core", difficulty: 2, text: "Объясните TCP/IP model." },
  { stage: "Core", difficulty: 2, text: "Что такое firewall?" },
  { stage: "Core", difficulty: 2, text: "Объясните SSL/TLS." },
  { stage: "Core", difficulty: 2, text: "Как работает VPN?" },
  { stage: "Core", difficulty: 3, text: "Как вы организуете CI/CD pipeline?", expectedKeywords: ["stages", "testing", "deployment"] },
  { stage: "Core", difficulty: 3, text: "Объясните GitOps." },
  { stage: "Core", difficulty: 3, text: "Что такое blue-green deployment?" },
  { stage: "Core", difficulty: 3, text: "Объясните canary deployment." },
  { stage: "Core", difficulty: 3, text: "Как работает autoscaling?" },
  { stage: "Core", difficulty: 3, text: "Что такое service mesh?" },
  { stage: "Core", difficulty: 3, text: "Объясните distributed tracing." },
  { stage: "Core", difficulty: 3, text: "Как настроить alerting?" },
  { stage: "Core", difficulty: 3, text: "Что такое chaos engineering?" },
  { stage: "Core", difficulty: 3, text: "Объясните backup strategies." },
  { stage: "Core", difficulty: 3, text: "Как работает database replication?" },
  { stage: "Core", difficulty: 3, text: "Что такое CDN?" },
  { stage: "Core", difficulty: 3, text: "Объясните secrets management." },
  { stage: "Core", difficulty: 3, text: "Как работает IAM?" },
  { stage: "Core", difficulty: 3, text: "Что такое network policies в Kubernetes?" },
  { stage: "Core", difficulty: 4, text: "Как вы проектируете высокодоступную инфраструктуру?", expectedKeywords: ["redundancy", "failover", "multi-AZ"] },
  { stage: "Core", difficulty: 4, text: "Объясните multi-cluster Kubernetes." },
  { stage: "Core", difficulty: 4, text: "Что такое Federation?" },
  { stage: "Core", difficulty: 4, text: "Как работает Istio?" },
  { stage: "Core", difficulty: 4, text: "Объясните eBPF." },
  { stage: "Core", difficulty: 4, text: "Что такое Knative?" },
  { stage: "Core", difficulty: 4, text: "Объясните operators в Kubernetes." },
  { stage: "Core", difficulty: 4, text: "Как работает custom controller?" },
  { stage: "Core", difficulty: 4, text: "Что такое Platform Engineering?" },
  { stage: "Core", difficulty: 4, text: "Объясните Internal Developer Platform." },
  { stage: "Core", difficulty: 5, text: "Как вы проектируете multi-region инфраструктуру?" },
  { stage: "Core", difficulty: 5, text: "Объясните global load balancing." },
  { stage: "Core", difficulty: 5, text: "Что такое data sovereignty?" },
  { stage: "Core", difficulty: 5, text: "Объясните compliance automation." },
  { stage: "Core", difficulty: 5, text: "Как работает FinOps?" },
  { stage: "Core", difficulty: 5, text: "Объясните cost allocation." },
  { stage: "Core", difficulty: 5, text: "Что такое zero trust security?" },
  { stage: "Core", difficulty: 5, text: "Объясните supply chain security." },
  { stage: "Core", difficulty: 5, text: "Как работает SBOM?" },
  { stage: "Core", difficulty: 5, text: "Объясните policy as code." },

  // ========== DEEP DIVE (40) ==========
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о сложном инциденте, который вы разрешали." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы настраивали мониторинг?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с container orchestration." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете logging?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с database management." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы автоматизируете рутинные задачи?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с network troubleshooting." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете secrets rotation?" },
  { stage: "DeepDive", difficulty: 4, text: "Опишите процесс миграции на Kubernetes." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы проводите post-mortem?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с capacity planning." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы настраиваете disaster recovery?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с security hardening." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с technical debt в инфраструктуре?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с cost optimization." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете documentation?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с compliance audits." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы обучаете разработчиков DevOps практикам?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о построении platform team." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы определяете SLO/SLA?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с multi-cloud." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете on-call rotation?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с zero-downtime migrations." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с vendor management?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с regulatory compliance." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете environments (dev, staging, prod)?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с artifact management." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с stateful applications?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с message queues deployment." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете database migrations?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с GitOps." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с hybrid cloud?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с edge computing." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете observability?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с AIOps." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с infrastructure testing?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с self-healing systems." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете change management?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с performance engineering." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с release management?" },

  // ========== CASE (25) ==========
  { stage: "Case", difficulty: 2, text: "Как бы вы настроили CI/CD для простого приложения?" },
  { stage: "Case", difficulty: 2, text: "Спроектируйте инфраструктуру для веб-приложения." },
  { stage: "Case", difficulty: 2, text: "Как бы вы настроили мониторинг для сервиса?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте инфраструктуру для microservices." },
  { stage: "Case", difficulty: 3, text: "Как бы вы организовали blue-green deployment?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте disaster recovery plan." },
  { stage: "Case", difficulty: 3, text: "Как бы вы настроили autoscaling?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте logging infrastructure." },
  { stage: "Case", difficulty: 4, text: "Спроектируйте инфраструктуру для 99.99% availability." },
  { stage: "Case", difficulty: 4, text: "Как бы вы мигрировали с монолита на microservices?" },
  { stage: "Case", difficulty: 4, text: "Спроектируйте internal developer platform." },
  { stage: "Case", difficulty: 4, text: "Как бы вы настроили multi-tenant Kubernetes?" },
  { stage: "Case", difficulty: 4, text: "Спроектируйте secrets management solution." },
  { stage: "Case", difficulty: 4, text: "Как бы вы организовали database high availability?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте multi-region active-active infrastructure." },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали zero-trust network?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте cost-optimized cloud architecture." },
  { stage: "Case", difficulty: 5, text: "Как бы вы мигрировали на multi-cloud?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте compliance-ready infrastructure." },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали infrastructure для AI/ML workloads?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте self-service platform для разработчиков." },
  { stage: "Case", difficulty: 5, text: "Как бы вы настроили chaos engineering?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте observability platform." },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали infrastructure для real-time data?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте platform для edge computing." },

  // ========== DEBUG (15) ==========
  { stage: "Debug", difficulty: 2, text: "Контейнер не запускается. Как найдёте причину?" },
  { stage: "Debug", difficulty: 2, text: "Pod в статусе CrashLoopBackOff. Что делать?" },
  { stage: "Debug", difficulty: 3, text: "Сервис недоступен, но поды работают. Как расследуете?" },
  { stage: "Debug", difficulty: 3, text: "Высокий CPU usage на нодах. Как диагностируете?" },
  { stage: "Debug", difficulty: 3, text: "Network connectivity issues между сервисами." },
  { stage: "Debug", difficulty: 3, text: "Deployment застрял. Как найдёте причину?" },
  { stage: "Debug", difficulty: 4, text: "Кластер работает нестабильно. Как расследуете?" },
  { stage: "Debug", difficulty: 4, text: "SSL certificate issues. Как диагностируете?" },
  { stage: "Debug", difficulty: 4, text: "DNS resolution медленный. Как исправите?" },
  { stage: "Debug", difficulty: 4, text: "Ingress не маршрутизирует трафик. Что делать?" },
  { stage: "Debug", difficulty: 5, text: "Cascading failure в production. Как остановите?" },
  { stage: "Debug", difficulty: 5, text: "Data corruption после миграции. Как восстановите?" },
  { stage: "Debug", difficulty: 5, text: "Security incident detected. Ваши действия?" },
  { stage: "Debug", difficulty: 5, text: "Cloud costs unexpectedly spiked. Как расследуете?" },
  { stage: "Debug", difficulty: 5, text: "Compliance audit failed. Как исправите?" },

  // ========== WRAPUP (10) ==========
  { stage: "WrapUp", difficulty: 1, text: "Что вам нравится в DevOps/SRE?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие технологии хотите изучить?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы следите за новыми трендами?" },
  { stage: "WrapUp", difficulty: 3, text: "Какой cloud provider предпочитаете и почему?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы относитесь к serverless?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в DevOps вы считаете важными?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы видите развитие Platform Engineering?" },
  { stage: "WrapUp", difficulty: 5, text: "Какой вклад вы хотите внести в индустрию?" },
  { stage: "WrapUp", difficulty: 5, text: "Как изменится DevOps в будущем?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие технические challenges вас привлекают?" },
];

