// frontend.ts - 200+ вопросов для Frontend Developer

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const frontendQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (25) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте frontend разработки." },
  { stage: "Background", difficulty: 1, text: "Какие фреймворки вы использовали?", expectedKeywords: ["React", "Vue", "Angular"] },
  { stage: "Background", difficulty: 1, text: "Как вы пришли в frontend разработку?" },
  { stage: "Background", difficulty: 1, text: "Какое у вас образование?" },
  { stage: "Background", difficulty: 1, text: "С какими проектами вы работали?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о самом интересном проекте." },
  { stage: "Background", difficulty: 2, text: "Как была организована работа в вашей команде?" },
  { stage: "Background", difficulty: 2, text: "С какими дизайнерами вы работали?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашем опыте работы с дизайн-системами." },
  { stage: "Background", difficulty: 2, text: "Какие инструменты разработки вы используете?" },
  { stage: "Background", difficulty: 3, text: "Опишите архитектуру frontend приложения, которое вы создавали." },
  { stage: "Background", difficulty: 3, text: "Как вы взаимодействовали с backend-разработчиками?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте оптимизации производительности." },
  { stage: "Background", difficulty: 3, text: "Как вы организовывали code review?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте менторства." },
  { stage: "Background", difficulty: 4, text: "Как вы принимали архитектурные решения?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте технического лидерства." },
  { stage: "Background", difficulty: 4, text: "Как вы внедряли новые технологии в команде?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте работы с legacy кодом." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли техническую стратегию?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте построения дизайн-системы." },
  { stage: "Background", difficulty: 5, text: "Как вы оценивали technical debt?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте построения команды." },
  { stage: "Background", difficulty: 5, text: "Как вы работали с cross-functional проектами?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о самом масштабном проекте." },

  // ========== CORE (70) ==========
  { stage: "Core", difficulty: 1, text: "Что такое HTML, CSS, JavaScript?", expectedKeywords: ["HTML", "CSS", "JavaScript"] },
  { stage: "Core", difficulty: 1, text: "Объясните box model в CSS." },
  { stage: "Core", difficulty: 1, text: "Что такое Flexbox?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое DOM." },
  { stage: "Core", difficulty: 1, text: "Что такое событие (event) в JavaScript?" },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между let, const и var." },
  { stage: "Core", difficulty: 1, text: "Что такое массив и объект в JavaScript?" },
  { stage: "Core", difficulty: 1, text: "Объясните callback функцию." },
  { stage: "Core", difficulty: 1, text: "Что такое responsive design?" },
  { stage: "Core", difficulty: 2, text: "Как работает Virtual DOM в React?", expectedKeywords: ["Virtual DOM", "reconciliation", "diff"] },
  { stage: "Core", difficulty: 2, text: "Объясните lifecycle методы компонента." },
  { stage: "Core", difficulty: 2, text: "Что такое hooks в React?", expectedKeywords: ["useState", "useEffect", "hooks"] },
  { stage: "Core", difficulty: 2, text: "Объясните state management." },
  { stage: "Core", difficulty: 2, text: "Что такое Promise и async/await?" },
  { stage: "Core", difficulty: 2, text: "Объясните event bubbling и capturing." },
  { stage: "Core", difficulty: 2, text: "Что такое closures в JavaScript?" },
  { stage: "Core", difficulty: 2, text: "Объясните this в JavaScript." },
  { stage: "Core", difficulty: 2, text: "Что такое TypeScript и зачем он нужен?" },
  { stage: "Core", difficulty: 2, text: "Объясните CSS preprocessors (SASS, LESS)." },
  { stage: "Core", difficulty: 2, text: "Что такое CSS Grid?" },
  { stage: "Core", difficulty: 2, text: "Объясните media queries." },
  { stage: "Core", difficulty: 2, text: "Что такое SPA (Single Page Application)?" },
  { stage: "Core", difficulty: 2, text: "Объясните client-side routing." },
  { stage: "Core", difficulty: 3, text: "Как вы организуете state management в большом приложении?", expectedKeywords: ["Redux", "MobX", "Context"] },
  { stage: "Core", difficulty: 3, text: "Объясните разницу между controlled и uncontrolled components." },
  { stage: "Core", difficulty: 3, text: "Что такое Higher-Order Components (HOC)?" },
  { stage: "Core", difficulty: 3, text: "Объясните render props pattern." },
  { stage: "Core", difficulty: 3, text: "Что такое code splitting?" },
  { stage: "Core", difficulty: 3, text: "Объясните lazy loading." },
  { stage: "Core", difficulty: 3, text: "Как работает SSR (Server-Side Rendering)?", expectedKeywords: ["SSR", "Next.js", "hydration"] },
  { stage: "Core", difficulty: 3, text: "Что такое Static Site Generation (SSG)?" },
  { stage: "Core", difficulty: 3, text: "Объясните Web Vitals (LCP, FID, CLS)." },
  { stage: "Core", difficulty: 3, text: "Как вы оптимизируете bundle size?" },
  { stage: "Core", difficulty: 3, text: "Что такое tree shaking?" },
  { stage: "Core", difficulty: 3, text: "Объясните CSS-in-JS." },
  { stage: "Core", difficulty: 3, text: "Что такое atomic CSS (Tailwind)?" },
  { stage: "Core", difficulty: 3, text: "Объясните accessibility (a11y)." },
  { stage: "Core", difficulty: 3, text: "Что такое ARIA?" },
  { stage: "Core", difficulty: 4, text: "Как вы проектируете компонентную архитектуру?", expectedKeywords: ["atomic design", "composition", "reusability"] },
  { stage: "Core", difficulty: 4, text: "Объясните micro-frontends." },
  { stage: "Core", difficulty: 4, text: "Что такое Module Federation?" },
  { stage: "Core", difficulty: 4, text: "Как работает WebAssembly?" },
  { stage: "Core", difficulty: 4, text: "Объясните Service Workers и PWA." },
  { stage: "Core", difficulty: 4, text: "Что такое Web Workers?" },
  { stage: "Core", difficulty: 4, text: "Объясните IndexedDB." },
  { stage: "Core", difficulty: 4, text: "Как работает WebGL?" },
  { stage: "Core", difficulty: 4, text: "Объясните Content Security Policy (CSP)." },
  { stage: "Core", difficulty: 4, text: "Что такое CORS?" },
  { stage: "Core", difficulty: 5, text: "Как вы проектируете frontend для миллионов пользователей?" },
  { stage: "Core", difficulty: 5, text: "Объясните rendering strategies (CSR, SSR, SSG, ISR)." },
  { stage: "Core", difficulty: 5, text: "Как работает browser rendering pipeline?" },
  { stage: "Core", difficulty: 5, text: "Объясните JavaScript event loop." },
  { stage: "Core", difficulty: 5, text: "Как работает garbage collection в JavaScript?" },
  { stage: "Core", difficulty: 5, text: "Объясните HTTP/2 и HTTP/3." },
  { stage: "Core", difficulty: 5, text: "Что такое edge computing?" },
  { stage: "Core", difficulty: 5, text: "Объясните React Server Components." },
  { stage: "Core", difficulty: 5, text: "Как работает Suspense?" },
  { stage: "Core", difficulty: 5, text: "Объясните concurrent rendering в React." },

  // ========== DEEP DIVE (40) ==========
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о сложной UI проблеме, которую вы решали." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы оптимизировали производительность приложения?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте работы с формами." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете тестирование frontend?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с анимациями." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы работаете с API?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с real-time features." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете error handling?" },
  { stage: "DeepDive", difficulty: 4, text: "Опишите ваш подход к созданию дизайн-системы." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы проводите code review?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с performance profiling." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы настраиваете CI/CD для frontend?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с монорепозиториями." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с feature flags?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с A/B тестами." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете локализацию (i18n)?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с dark mode." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с большими списками (virtualization)?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о сложном архитектурном решении." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете работу с technical debt?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с миграцией на новый фреймворк." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы обеспечиваете accessibility?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с SEO." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с offline-first приложениями?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с cross-browser compatibility." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы организуете структуру проекта?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с webpack/vite." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с images optimization?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с fonts loading." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете caching strategy?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с third-party scripts." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с complex forms (multi-step, dynamic)?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с data visualization." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете state persistence?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с collaborative features." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с file uploads?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с drag-and-drop." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете keyboard navigation?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с mobile-first design." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с touch events?" },

  // ========== CASE (25) ==========
  { stage: "Case", difficulty: 2, text: "Как бы вы создали компонент модального окна?" },
  { stage: "Case", difficulty: 2, text: "Спроектируйте компонент autocomplete." },
  { stage: "Case", difficulty: 2, text: "Как бы вы реализовали infinite scroll?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте компонент таблицы с сортировкой и фильтрацией." },
  { stage: "Case", difficulty: 3, text: "Как бы вы создали drag-and-drop список?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте компонент calendar/date picker." },
  { stage: "Case", difficulty: 3, text: "Как бы вы реализовали real-time notifications?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте форму с валидацией." },
  { stage: "Case", difficulty: 4, text: "Спроектируйте дизайн-систему с нуля." },
  { stage: "Case", difficulty: 4, text: "Как бы вы создали WYSIWYG редактор?" },
  { stage: "Case", difficulty: 4, text: "Спроектируйте компонент file uploader с progress." },
  { stage: "Case", difficulty: 4, text: "Как бы вы создали dashboard с виджетами?" },
  { stage: "Case", difficulty: 4, text: "Спроектируйте систему навигации для SPA." },
  { stage: "Case", difficulty: 4, text: "Как бы вы реализовали theming system?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте frontend для e-commerce с фильтрами, корзиной, checkout." },
  { stage: "Case", difficulty: 5, text: "Как бы вы создали collaborative document editor (типа Google Docs)?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте video player с custom controls." },
  { stage: "Case", difficulty: 5, text: "Как бы вы создали map-based приложение?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте social media feed с infinite scroll и caching." },
  { stage: "Case", difficulty: 5, text: "Как бы вы создали spreadsheet component?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте image editor в браузере." },
  { stage: "Case", difficulty: 5, text: "Как бы вы создали code editor (Monaco-like)?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте kanban board." },
  { stage: "Case", difficulty: 5, text: "Как бы вы создали chat interface с real-time messaging?" },
  { stage: "Case", difficulty: 5, text: "Спроектируйте analytics dashboard с charts." },

  // ========== DEBUG (15) ==========
  { stage: "Debug", difficulty: 2, text: "Страница грузится медленно. Как найдёте причину?" },
  { stage: "Debug", difficulty: 2, text: "Компонент не перерендеривается при изменении state." },
  { stage: "Debug", difficulty: 3, text: "Memory leak в React приложении. Как найдёте?" },
  { stage: "Debug", difficulty: 3, text: "Layout shift происходит при загрузке. Как исправите?" },
  { stage: "Debug", difficulty: 3, text: "Bundle size слишком большой. Как уменьшите?" },
  { stage: "Debug", difficulty: 3, text: "Event handler вызывается несколько раз." },
  { stage: "Debug", difficulty: 4, text: "Infinite loop в useEffect. Как диагностируете?" },
  { stage: "Debug", difficulty: 4, text: "Race condition при асинхронных запросах." },
  { stage: "Debug", difficulty: 4, text: "CSS не применяется к компоненту. Как дебажите?" },
  { stage: "Debug", difficulty: 4, text: "Hydration mismatch в SSR приложении." },
  { stage: "Debug", difficulty: 5, text: "Rendering bottleneck при большом количестве данных." },
  { stage: "Debug", difficulty: 5, text: "Security vulnerability (XSS) обнаружена. Как исправите?" },
  { stage: "Debug", difficulty: 5, text: "Приложение падает в production, но работает в dev." },
  { stage: "Debug", difficulty: 5, text: "Third-party script замедляет страницу." },
  { stage: "Debug", difficulty: 5, text: "State corruption в complex form." },

  // ========== WRAPUP (10) ==========
  { stage: "WrapUp", difficulty: 1, text: "Что вам нравится в frontend разработке?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие технологии хотите изучить?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы следите за новыми трендами?" },
  { stage: "WrapUp", difficulty: 3, text: "Какой фреймворк предпочитаете и почему?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы относитесь к TypeScript?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в frontend вы считаете важными?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы видите развитие web платформы?" },
  { stage: "WrapUp", difficulty: 5, text: "Какой вклад вы хотите внести в индустрию?" },
  { stage: "WrapUp", difficulty: 5, text: "Как изменится frontend разработка в будущем?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие технические challenges вас привлекают?" },
];

