// product.ts - 200+ вопросов для Product Manager

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const productQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (25) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте в продуктовом менеджменте." },
  { stage: "Background", difficulty: 1, text: "Какие продукты вы создавали или развивали?" },
  { stage: "Background", difficulty: 1, text: "Как вы пришли в продуктовый менеджмент?" },
  { stage: "Background", difficulty: 1, text: "Какое у вас образование?" },
  { stage: "Background", difficulty: 1, text: "С какими типами продуктов вы работали (B2B/B2C)?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о продукте, которым вы больше всего гордитесь." },
  { stage: "Background", difficulty: 2, text: "Как была организована продуктовая команда?" },
  { stage: "Background", difficulty: 2, text: "Какие инструменты вы использовали?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашем опыте работы с разработчиками." },
  { stage: "Background", difficulty: 2, text: "С какими метриками вы работали?" },
  { stage: "Background", difficulty: 3, text: "Опишите продуктовую стратегию, которую вы разрабатывали." },
  { stage: "Background", difficulty: 3, text: "Как вы взаимодействовали со stakeholders?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте запуска продукта." },
  { stage: "Background", difficulty: 3, text: "Какой был ваш вклад в рост продукта?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте менторства." },
  { stage: "Background", difficulty: 4, text: "Как вы определяли product vision?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте лидерства." },
  { stage: "Background", difficulty: 4, text: "Как вы работали с executive team?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте с product-led growth." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли продуктовую стратегию компании?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте с board reporting." },
  { stage: "Background", difficulty: 5, text: "Как вы оценивали ROI продуктовых инициатив?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте построения команды." },
  { stage: "Background", difficulty: 5, text: "Как вы работали с M&A в контексте продукта?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о самом сложном продуктовом решении." },

  // ========== CORE (70) ==========
  { stage: "Core", difficulty: 1, text: "Что такое product roadmap?", expectedKeywords: ["roadmap", "приоритеты", "timeline"] },
  { stage: "Core", difficulty: 1, text: "Объясните роль продуктового менеджера." },
  { stage: "Core", difficulty: 1, text: "Что такое user story?" },
  { stage: "Core", difficulty: 1, text: "Объясните MVP." },
  { stage: "Core", difficulty: 1, text: "Что такое backlog?" },
  { stage: "Core", difficulty: 1, text: "Объясните sprint в Agile." },
  { stage: "Core", difficulty: 1, text: "Что такое stakeholder?" },
  { stage: "Core", difficulty: 1, text: "Объясните PRD (Product Requirements Document)." },
  { stage: "Core", difficulty: 1, text: "Что такое feature?" },
  { stage: "Core", difficulty: 2, text: "Как вы приоритизируете фичи?", expectedKeywords: ["RICE", "impact", "effort"] },
  { stage: "Core", difficulty: 2, text: "Объясните RICE framework." },
  { stage: "Core", difficulty: 2, text: "Что такое product discovery?" },
  { stage: "Core", difficulty: 2, text: "Объясните user research." },
  { stage: "Core", difficulty: 2, text: "Что такое product-market fit?" },
  { stage: "Core", difficulty: 2, text: "Объясните OKRs." },
  { stage: "Core", difficulty: 2, text: "Что такое north star metric?" },
  { stage: "Core", difficulty: 2, text: "Объясните retention, engagement, growth metrics." },
  { stage: "Core", difficulty: 2, text: "Что такое A/B testing в продукте?" },
  { stage: "Core", difficulty: 2, text: "Объясните customer journey." },
  { stage: "Core", difficulty: 2, text: "Что такое persona?" },
  { stage: "Core", difficulty: 2, text: "Объясните Jobs-to-be-Done framework." },
  { stage: "Core", difficulty: 2, text: "Что такое competitive analysis?" },
  { stage: "Core", difficulty: 2, text: "Объясните product analytics." },
  { stage: "Core", difficulty: 3, text: "Как вы строите product strategy?", expectedKeywords: ["vision", "goals", "roadmap"] },
  { stage: "Core", difficulty: 3, text: "Объясните product vision vs strategy vs roadmap." },
  { stage: "Core", difficulty: 3, text: "Что такое opportunity assessment?" },
  { stage: "Core", difficulty: 3, text: "Объясните outcome-based roadmapping." },
  { stage: "Core", difficulty: 3, text: "Как работает continuous discovery?" },
  { stage: "Core", difficulty: 3, text: "Что такое prototype testing?" },
  { stage: "Core", difficulty: 3, text: "Объясните product launch process." },
  { stage: "Core", difficulty: 3, text: "Что такое feature flagging?" },
  { stage: "Core", difficulty: 3, text: "Объясните technical debt в контексте продукта." },
  { stage: "Core", difficulty: 3, text: "Как работает cross-functional collaboration?" },
  { stage: "Core", difficulty: 3, text: "Что такое stakeholder management?" },
  { stage: "Core", difficulty: 3, text: "Объясните product metrics hierarchy." },
  { stage: "Core", difficulty: 3, text: "Как работает funnel analysis?" },
  { stage: "Core", difficulty: 3, text: "Что такое cohort analysis в продукте?" },
  { stage: "Core", difficulty: 3, text: "Объясните experimentation framework." },
  { stage: "Core", difficulty: 4, text: "Как вы строите product organization?", expectedKeywords: ["teams", "structure", "ownership"] },
  { stage: "Core", difficulty: 4, text: "Объясните platform vs feature teams." },
  { stage: "Core", difficulty: 4, text: "Что такое product ops?" },
  { stage: "Core", difficulty: 4, text: "Объясните dual-track development." },
  { stage: "Core", difficulty: 4, text: "Как работает product-led growth?" },
  { stage: "Core", difficulty: 4, text: "Что такое monetization strategy?" },
  { stage: "Core", difficulty: 4, text: "Объясните pricing strategy." },
  { stage: "Core", difficulty: 4, text: "Как работает international product expansion?" },
  { stage: "Core", difficulty: 4, text: "Что такое platform strategy?" },
  { stage: "Core", difficulty: 4, text: "Объясните ecosystem thinking." },
  { stage: "Core", difficulty: 5, text: "Как вы определяете company-level product strategy?" },
  { stage: "Core", difficulty: 5, text: "Объясните portfolio management." },
  { stage: "Core", difficulty: 5, text: "Что такое product-led organization?" },
  { stage: "Core", difficulty: 5, text: "Объясните product culture." },
  { stage: "Core", difficulty: 5, text: "Как работает innovation management?" },
  { stage: "Core", difficulty: 5, text: "Что такое venture building внутри компании?" },
  { stage: "Core", difficulty: 5, text: "Объясните strategic planning для продукта." },
  { stage: "Core", difficulty: 5, text: "Как работает M&A integration для продуктов?" },
  { stage: "Core", difficulty: 5, text: "Что такое product market expansion?" },
  { stage: "Core", difficulty: 5, text: "Объясните technology-driven product innovation." },

  // ========== DEEP DIVE (40) ==========
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о фиче, которую было сложно приоритизировать." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы проводите user research?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем подходе к написанию PRD." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы работаете с разработчиками над scope?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с A/B тестами." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы анализируете product metrics?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с customer feedback." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы готовите product launch?" },
  { stage: "DeepDive", difficulty: 4, text: "Опишите ваш подход к product strategy." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с competing priorities?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с stakeholder conflicts." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы определяете success metrics?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с failed product/feature." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с technical constraints?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с pricing decisions." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете product reviews?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с competitive pressure." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с design team?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о построении product team." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы определяете product vision?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с pivots." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с board/investors?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с platform products." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите product culture?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с international expansion." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы используете data в принятии решений?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с roadmap communication." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с technical debt decisions?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с growth experiments." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете discovery process?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с platform ecosystem." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с regulatory constraints?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с AI/ML products." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете product operations?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с enterprise vs consumer products." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с marketplace products?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с subscription models." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете product analytics?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с product-led sales." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с developer products?" },

  // ========== CASE (25) ==========
  { stage: "Case", difficulty: 2, text: "Как бы вы приоритизировали эти 5 фич?" },
  { stage: "Case", difficulty: 2, text: "Спроектируйте MVP для нового продукта." },
  { stage: "Case", difficulty: 2, text: "Как бы вы определили success metrics для фичи?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы улучшили retention в приложении?" },
  { stage: "Case", difficulty: 3, text: "Спроектируйте roadmap на квартал." },
  { stage: "Case", difficulty: 3, text: "Как бы вы провели discovery для новой фичи?" },
  { stage: "Case", difficulty: 3, text: "Product metrics упали. Как расследуете?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы организовали A/B тест?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы определили product-market fit?" },
  { stage: "Case", difficulty: 4, text: "Stakeholders не согласны с roadmap. Ваши действия?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы монетизировали бесплатный продукт?" },
  { stage: "Case", difficulty: 4, text: "Конкурент запустил аналогичную фичу. Что делать?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы организовали product launch?" },
  { stage: "Case", difficulty: 4, text: "Technical team говорит, что это займёт 6 месяцев. Как отреагируете?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили product strategy для стартапа?" },
  { stage: "Case", difficulty: 5, text: "Компания хочет выйти на новый рынок. Ваш план?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали platform product?" },
  { stage: "Case", difficulty: 5, text: "Product-led vs sales-led growth. Как выберете?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы интегрировали acquired product?" },
  { stage: "Case", difficulty: 5, text: "Нужно сократить scope на 50%. Как подойдёте?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили ecosystem strategy?" },
  { stage: "Case", difficulty: 5, text: "Product не достигает targets. Ваш план?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали international product launch?" },
  { stage: "Case", difficulty: 5, text: "Legacy product vs new investment. Как приоритизируете?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили AI product strategy?" },

  // ========== DEBUG (15) ==========
  { stage: "Debug", difficulty: 2, text: "Feature launch не показывает ожидаемые результаты. Как анализируете?" },
  { stage: "Debug", difficulty: 2, text: "User feedback противоречит data. Как разберётесь?" },
  { stage: "Debug", difficulty: 3, text: "Retention упал после релиза. Как расследуете?" },
  { stage: "Debug", difficulty: 3, text: "A/B тест показывает unexpected results. Что делать?" },
  { stage: "Debug", difficulty: 3, text: "Team не успевает по roadmap. Как адаптируете?" },
  { stage: "Debug", difficulty: 3, text: "Stakeholder недоволен progress. Как разрешите?" },
  { stage: "Debug", difficulty: 4, text: "Product metrics не коррелируют с business metrics. Как исправите?" },
  { stage: "Debug", difficulty: 4, text: "Technical debt блокирует развитие. Как приоритизируете?" },
  { stage: "Debug", difficulty: 4, text: "Competitor захватывает market share. Ваши действия?" },
  { stage: "Debug", difficulty: 4, text: "User churn растёт. Как диагностируете?" },
  { stage: "Debug", difficulty: 5, text: "Product strategy не работает. Как pivot?" },
  { stage: "Debug", difficulty: 5, text: "Team morale низкий после failed launch. Как recovery?" },
  { stage: "Debug", difficulty: 5, text: "Board не согласен с direction. Как убедите?" },
  { stage: "Debug", difficulty: 5, text: "Market shift требует major pivot. Как организуете?" },
  { stage: "Debug", difficulty: 5, text: "Key metric отрицательный ROI. Как proceed?" },

  // ========== WRAPUP (10) ==========
  { stage: "WrapUp", difficulty: 1, text: "Что вам нравится в продуктовом менеджменте?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие навыки хотите развить?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы следите за product trends?" },
  { stage: "WrapUp", difficulty: 3, text: "Какой тип продуктов предпочитаете и почему?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы относитесь к data vs intuition?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в PM вы считаете важными?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы видите влияние AI на продуктовый менеджмент?" },
  { stage: "WrapUp", difficulty: 5, text: "Какой вклад вы хотите внести в product community?" },
  { stage: "WrapUp", difficulty: 5, text: "Как изменится роль PM в будущем?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие challenges вас привлекают?" },
];

