// sales.ts - 200+ вопросов для Sales / Account Manager / Seller Manager

type Stage = "Background" | "Core" | "SQL" | "DeepDive" | "Case" | "Debug" | "WrapUp";
type Difficulty = 1 | 2 | 3 | 4 | 5;
type QuestionEntry = { text: string; stage: Stage; difficulty: Difficulty; tags?: string[]; expectedKeywords?: string[] };

export const salesQuestions: QuestionEntry[] = [
  // ========== BACKGROUND (25) ==========
  { stage: "Background", difficulty: 1, text: "Расскажите о вашем опыте в продажах." },
  { stage: "Background", difficulty: 1, text: "Какие продукты/услуги вы продавали?" },
  { stage: "Background", difficulty: 1, text: "Как вы пришли в продажи?" },
  { stage: "Background", difficulty: 1, text: "Какое у вас образование?" },
  { stage: "Background", difficulty: 1, text: "С какими типами клиентов вы работали (B2B/B2C)?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашей самой крупной сделке." },
  { stage: "Background", difficulty: 2, text: "Как была организована команда продаж?" },
  { stage: "Background", difficulty: 2, text: "Какие CRM системы вы использовали?" },
  { stage: "Background", difficulty: 2, text: "Расскажите о вашем опыте холодных звонков." },
  { stage: "Background", difficulty: 2, text: "С какими объемами продаж вы работали?" },
  { stage: "Background", difficulty: 3, text: "Опишите ваш sales process от start до close." },
  { stage: "Background", difficulty: 3, text: "Как вы взаимодействовали с маркетингом?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте работы с enterprise клиентами." },
  { stage: "Background", difficulty: 3, text: "Какой был ваш quota attainment?" },
  { stage: "Background", difficulty: 3, text: "Расскажите о вашем опыте менторства." },
  { stage: "Background", difficulty: 4, text: "Как вы строили территорию с нуля?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте лидерства в продажах." },
  { stage: "Background", difficulty: 4, text: "Как вы работали со сложными переговорами?" },
  { stage: "Background", difficulty: 4, text: "Расскажите о вашем опыте с channel partners." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли sales strategy?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте построения команды." },
  { stage: "Background", difficulty: 5, text: "Как вы работали с C-level клиентами?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о вашем опыте с international sales." },
  { stage: "Background", difficulty: 5, text: "Как вы определяли pricing strategy?" },
  { stage: "Background", difficulty: 5, text: "Расскажите о самой сложной сделке, которую вы закрыли." },

  // ========== CORE (70) ==========
  { stage: "Core", difficulty: 1, text: "Что такое sales funnel?", expectedKeywords: ["воронка", "lead", "conversion"] },
  { stage: "Core", difficulty: 1, text: "Объясните разницу между B2B и B2C продажами." },
  { stage: "Core", difficulty: 1, text: "Что такое lead и opportunity?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое quota." },
  { stage: "Core", difficulty: 1, text: "Что такое pipeline?" },
  { stage: "Core", difficulty: 1, text: "Объясните cold calling." },
  { stage: "Core", difficulty: 1, text: "Что такое CRM?" },
  { stage: "Core", difficulty: 1, text: "Объясните, что такое upselling и cross-selling." },
  { stage: "Core", difficulty: 1, text: "Что такое closing?" },
  { stage: "Core", difficulty: 2, text: "Как вы квалифицируете лиды?", expectedKeywords: ["BANT", "qualification", "budget"] },
  { stage: "Core", difficulty: 2, text: "Объясните BANT framework." },
  { stage: "Core", difficulty: 2, text: "Что такое discovery call?" },
  { stage: "Core", difficulty: 2, text: "Объясните value proposition." },
  { stage: "Core", difficulty: 2, text: "Как работает consultative selling?" },
  { stage: "Core", difficulty: 2, text: "Что такое objection handling?" },
  { stage: "Core", difficulty: 2, text: "Объясните social selling." },
  { stage: "Core", difficulty: 2, text: "Что такое sales enablement?" },
  { stage: "Core", difficulty: 2, text: "Объясните forecasting." },
  { stage: "Core", difficulty: 2, text: "Что такое deal velocity?" },
  { stage: "Core", difficulty: 2, text: "Объясните win rate." },
  { stage: "Core", difficulty: 2, text: "Что такое average deal size?" },
  { stage: "Core", difficulty: 2, text: "Объясните sales cycle." },
  { stage: "Core", difficulty: 2, text: "Что такое churn и retention в контексте продаж?" },
  { stage: "Core", difficulty: 3, text: "Как вы строите account plan?", expectedKeywords: ["stakeholders", "strategy", "timeline"] },
  { stage: "Core", difficulty: 3, text: "Объясните MEDDIC/MEDDPICC." },
  { stage: "Core", difficulty: 3, text: "Что такое champion и economic buyer?" },
  { stage: "Core", difficulty: 3, text: "Объясните multi-threading." },
  { stage: "Core", difficulty: 3, text: "Как работает solution selling?" },
  { stage: "Core", difficulty: 3, text: "Что такое proof of concept?" },
  { stage: "Core", difficulty: 3, text: "Объясните negotiation tactics." },
  { stage: "Core", difficulty: 3, text: "Что такое competitive positioning?" },
  { stage: "Core", difficulty: 3, text: "Объясните ROI selling." },
  { stage: "Core", difficulty: 3, text: "Как работает account-based selling?" },
  { stage: "Core", difficulty: 3, text: "Что такое land and expand?" },
  { stage: "Core", difficulty: 3, text: "Объясните customer success в продажах." },
  { stage: "Core", difficulty: 3, text: "Что такое NPS и как он связан с продажами?" },
  { stage: "Core", difficulty: 3, text: "Объясните referral selling." },
  { stage: "Core", difficulty: 3, text: "Как работает partner/channel sales?" },
  { stage: "Core", difficulty: 4, text: "Как вы строите enterprise sales process?", expectedKeywords: ["complex", "stakeholders", "procurement"] },
  { stage: "Core", difficulty: 4, text: "Объясните strategic account management." },
  { stage: "Core", difficulty: 4, text: "Что такое executive sponsorship?" },
  { stage: "Core", difficulty: 4, text: "Объясните deal desk process." },
  { stage: "Core", difficulty: 4, text: "Как работает procurement cycle?" },
  { stage: "Core", difficulty: 4, text: "Что такое RFP/RFI process?" },
  { stage: "Core", difficulty: 4, text: "Объясните contract negotiation." },
  { stage: "Core", difficulty: 4, text: "Что такое legal review в сделках?" },
  { stage: "Core", difficulty: 4, text: "Объясните SLA в B2B продажах." },
  { stage: "Core", difficulty: 4, text: "Как работают professional services в продажах?" },
  { stage: "Core", difficulty: 5, text: "Как вы строите go-to-market strategy?" },
  { stage: "Core", difficulty: 5, text: "Объясните sales operations." },
  { stage: "Core", difficulty: 5, text: "Что такое sales compensation planning?" },
  { stage: "Core", difficulty: 5, text: "Объясните territory design." },
  { stage: "Core", difficulty: 5, text: "Как работает sales capacity planning?" },
  { stage: "Core", difficulty: 5, text: "Что такое sales methodology adoption?" },
  { stage: "Core", difficulty: 5, text: "Объясните revenue operations (RevOps)." },
  { stage: "Core", difficulty: 5, text: "Как работает sales analytics?" },
  { stage: "Core", difficulty: 5, text: "Что такое predictive sales analytics?" },
  { stage: "Core", difficulty: 5, text: "Объясните market expansion strategy." },

  // ========== DEEP DIVE (40) ==========
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о сделке, которую было сложно закрыть." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы справляетесь с возражениями?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем подходе к cold outreach." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы готовитесь к discovery call?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с demo presentations." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы работаете с long sales cycle?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем опыте с multiple stakeholders." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы приоритизируете pipeline?" },
  { stage: "DeepDive", difficulty: 4, text: "Опишите ваш подход к enterprise сделкам." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с procurement?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с contract negotiations." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы строите relationships с C-level?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с competitive deals." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с lost deals?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с expansion revenue." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете account reviews?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с sales forecasting." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с underperformance?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о построении sales team." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы определяете compensation plans?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с market entry." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с board reporting?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с M&A integration." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы строите partner ecosystem?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с international expansion." },
  { stage: "DeepDive", difficulty: 3, text: "Как вы используете CRM эффективно?" },
  { stage: "DeepDive", difficulty: 3, text: "Расскажите о вашем daily routine." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы работаете с sales enablement materials?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с customer references." },
  { stage: "DeepDive", difficulty: 4, text: "Как вы организуете QBRs с клиентами?" },
  { stage: "DeepDive", difficulty: 4, text: "Расскажите о вашем опыте с deal rescue." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с pricing exceptions?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с strategic partnerships." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете sales training?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с sales methodology implementation." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с sales data analysis?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с customer segmentation." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы организуете territory optimization?" },
  { stage: "DeepDive", difficulty: 5, text: "Расскажите о вашем опыте с revenue forecasting." },
  { stage: "DeepDive", difficulty: 5, text: "Как вы работаете с sales culture building?" },

  // ========== CASE (25) ==========
  { stage: "Case", difficulty: 2, text: "Как бы вы подготовились к cold call?" },
  { stage: "Case", difficulty: 2, text: "Клиент говорит 'слишком дорого'. Как ответите?" },
  { stage: "Case", difficulty: 2, text: "Как бы вы квалифицировали этот lead?" },
  { stage: "Case", difficulty: 3, text: "Клиент сравнивает вас с конкурентом. Как позиционируете?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы провели discovery с enterprise клиентом?" },
  { stage: "Case", difficulty: 3, text: "Сделка застряла. Как её продвинете?" },
  { stage: "Case", difficulty: 3, text: "Как бы вы составили proposal?" },
  { stage: "Case", difficulty: 3, text: "Клиент просит скидку 40%. Как отреагируете?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы построили account plan для крупного клиента?" },
  { stage: "Case", difficulty: 4, text: "Champion ушёл из компании. Ваши действия?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы организовали multi-year deal?" },
  { stage: "Case", difficulty: 4, text: "Procurement затягивает процесс. Что делать?" },
  { stage: "Case", difficulty: 4, text: "Как бы вы провели executive presentation?" },
  { stage: "Case", difficulty: 4, text: "Конкурент демпингует. Ваша стратегия?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили sales process с нуля?" },
  { stage: "Case", difficulty: 5, text: "Новый market segment. Как подойдёте к entry?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали partner program?" },
  { stage: "Case", difficulty: 5, text: "Team underperforming. Ваш план?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы оптимизировали territory coverage?" },
  { stage: "Case", difficulty: 5, text: "Merger с competitor. Как интегрируете sales teams?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили sales enablement program?" },
  { stage: "Case", difficulty: 5, text: "New product launch. Ваш GTM план?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы организовали international expansion?" },
  { stage: "Case", difficulty: 5, text: "Customer churn increasing. Ваши действия?" },
  { stage: "Case", difficulty: 5, text: "Как бы вы построили predictive forecasting?" },

  // ========== DEBUG (15) ==========
  { stage: "Debug", difficulty: 2, text: "Pipeline не конвертируется. Как найдёте причину?" },
  { stage: "Debug", difficulty: 2, text: "Cold outreach не работает. Что измените?" },
  { stage: "Debug", difficulty: 3, text: "Deals постоянно откладываются. Как расследуете?" },
  { stage: "Debug", difficulty: 3, text: "Win rate упал. Как анализируете?" },
  { stage: "Debug", difficulty: 3, text: "Высокий churn после продажи. Как исправите?" },
  { stage: "Debug", difficulty: 3, text: "Team не достигает quota. Что делать?" },
  { stage: "Debug", difficulty: 4, text: "Forecast постоянно неточный. Как улучшите?" },
  { stage: "Debug", difficulty: 4, text: "Sales cycle удлинился. Как оптимизируете?" },
  { stage: "Debug", difficulty: 4, text: "Lost deal post-mortem. Как проводите?" },
  { stage: "Debug", difficulty: 4, text: "CRM adoption низкий. Как исправите?" },
  { stage: "Debug", difficulty: 5, text: "Revenue miss в quarter. Как recovery планируете?" },
  { stage: "Debug", difficulty: 5, text: "Key account churned. Как предотвратите в будущем?" },
  { stage: "Debug", difficulty: 5, text: "Top performer уходит. Как сохраните knowledge?" },
  { stage: "Debug", difficulty: 5, text: "Market shift. Как адаптируете strategy?" },
  { stage: "Debug", difficulty: 5, text: "Board недоволен results. Ваш план действий?" },

  // ========== WRAPUP (10) ==========
  { stage: "WrapUp", difficulty: 1, text: "Что вам нравится в продажах?" },
  { stage: "WrapUp", difficulty: 2, text: "Какие навыки хотите развить?" },
  { stage: "WrapUp", difficulty: 2, text: "Как вы справляетесь с rejection?" },
  { stage: "WrapUp", difficulty: 3, text: "Какой тип продаж предпочитаете и почему?" },
  { stage: "WrapUp", difficulty: 3, text: "Как вы мотивируете себя?" },
  { stage: "WrapUp", difficulty: 4, text: "Какие тренды в продажах вы считаете важными?" },
  { stage: "WrapUp", difficulty: 4, text: "Как вы видите влияние AI на продажи?" },
  { stage: "WrapUp", difficulty: 5, text: "Какой вклад вы хотите внести в sales profession?" },
  { stage: "WrapUp", difficulty: 5, text: "Как изменятся продажи в будущем?" },
  { stage: "WrapUp", difficulty: 5, text: "Какие challenges в sales вас привлекают?" },
];

